/**
 * Settings ▸ Mode — `docs/reference/app-modes.md` §3.4.
 *
 * Lazily imported: `Settings.tsx` is baselined at 1,815 lines and must never
 * inline a pane.
 *
 * The "what each mode changes" disclosure is generated by diffing the target
 * manifest against Classic's, so the explanation cannot drift from what the mode
 * actually does — it is the same data that drives the behaviour.
 */

import { useMemo } from 'react'
import { APP_MODE_OPTIONS, type AppModeId } from '../../../../shared/app-mode/app-mode-id'
import { diffSurfacesAgainstClassic } from '../../../../shared/app-mode/app-mode-capability'
import { translate } from '@/i18n/i18n'

export type AppModePaneProps = {
  mode: AppModeId
  /** True when ORCA_APP_MODE or the sidecar lock owns the choice (§2.8). */
  locked: boolean
  lockReason: string | null
  /** Set when the settings file names a mode we do not recognize. The file is
   *  never overwritten, so the user keeps whatever they typed. */
  unrecognizedMode: string | null
  onSelect: (mode: AppModeId) => void
  onRevealSettingsFile: () => void
}

const MODE_SUMMARY: Record<AppModeId, { key: string; fallback: string }> = {
  classic: {
    key: 'appMode.classicDescription',
    fallback: 'Everything Orca can do, all on screen.'
  },
  alab: {
    key: 'appMode.alabDescription',
    fallback: 'A console for supervising a fleet of agents. Files and diffs are hidden, not closed.'
  },
  'story-world': {
    key: 'appMode.storyWorldDescription',
    fallback: 'A simple stage for building a world with an agent.'
  }
}

export default function AppModePane(props: AppModePaneProps): React.JSX.Element {
  const changes = useMemo(() => diffSurfacesAgainstClassic(props.mode), [props.mode])

  return (
    <div className="flex flex-col gap-4" data-testid="settings-app-mode-pane">
      {props.unrecognizedMode ? (
        <div
          role="status"
          className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm"
        >
          {translate(
            'appMode.unrecognized',
            'Your settings file names a mode Orca does not recognize. Orca is running in Classic.'
          )}{' '}
          <code>{props.unrecognizedMode}</code>
        </div>
      ) : null}

      <fieldset disabled={props.locked} className="flex flex-col gap-2">
        {APP_MODE_OPTIONS.map((option) => {
          const summary = MODE_SUMMARY[option.id]
          return (
            <label key={option.id} className="flex items-start gap-3 rounded-md border p-3">
              <input
                type="radio"
                name="app-mode"
                value={option.id}
                checked={option.id === props.mode}
                onChange={() => props.onSelect(option.id)}
              />
              <span className="flex flex-col gap-1">
                <span className="text-sm font-medium">
                  {translate(option.labelKey, option.id)}
                </span>
                <span className="text-muted-foreground text-xs">
                  {translate(summary.key, summary.fallback)}
                </span>
              </span>
            </label>
          )
        })}
      </fieldset>

      {props.locked && props.lockReason ? (
        <p className="text-muted-foreground text-xs">{props.lockReason}</p>
      ) : null}

      <details className="text-sm">
        <summary className="cursor-pointer">
          {translate('appMode.whatChanges', 'What this mode changes')}
        </summary>
        {changes.length === 0 ? (
          <p className="text-muted-foreground mt-2 text-xs">
            {translate('appMode.noChanges', 'Nothing is hidden. This is the full app.')}
          </p>
        ) : (
          <ul className="text-muted-foreground mt-2 list-disc pl-5 text-xs">
            {changes.map((surface) => (
              <li key={surface}>{surface}</li>
            ))}
          </ul>
        )}
      </details>

      <button
        type="button"
        className="self-start text-xs underline"
        onClick={props.onRevealSettingsFile}
      >
        {translate('appMode.revealFile', 'Reveal settings file')}
      </button>
    </div>
  )
}
