// The four work-derived branch-naming helpers on the Rust
// `orca_core::branch_name_from_work` core. This sits on `orca-dispatch-seam`
// rather than in one tree's binding directory because the callers span two
// trees and no single binding reaches both: main drives the rename hook
// (`agent-hooks/first-work-branch-rename.ts`,
// `agent-hooks/first-work-workspace-title-rename.ts`,
// `text-generation/commit-message-text-generation.ts`, napi) while the renderer
// draws a review draft title from the same humanizer
// (`right-sidebar/create-review-draft-title.ts`, wasm at ready). It replaces the
// pair `src/main/rust-branch-name-from-work.ts` +
// `src/renderer/src/lib/git-wasm/branch-name-from-work.ts`, whose renderer half
// carried three of the pre-ready violations in ported-modules.md.
// `buildBranchNamePrompt` deliberately stays in the twin — see its header.
//
// PRE-READY CONTRACT — `parity`, and it is FORCED, not tidy:
//  * `sanitizeBranchSlug`'s output is renamed onto a real branch
//    (`git branch -m`, `resolveUniqueBranchName`) and `humanizeBranchSlug`'s is
//    written straight to `deps.setDisplayName(worktreeId, …)`, i.e. persisted
//    workspace identity.
//  * No sentinel has anywhere to live. `''` is already each string function's
//    real answer for "nothing usable / prefix-only / empty slug", and every
//    caller reads it as exactly that (`if (!slug) return stop(…)`,
//    `humanizeBranchSlug(leaf) || normalizedBranch`).
//    `isAutoGeneratedCreatureBranchName` is a total predicate GATING a
//    destructive rewrite: `false` skips the rename for the whole session,
//    `true` overwrites a branch the user may have named.
// So each fallback recomputes the deleted twin's body over the kept
// `MARINE_CREATURES` table and `MAX_BRANCH_NAME_WORDS`.
//
// MEASURED, not assumed: 16.1M differential probes of the fallbacks below
// against BOTH shipped cores (9.34M vs `orca_git_wasm_bg.wasm`, 6.80M vs
// `orca_node.node`) — every Unicode scalar in four positions, all 552 creature
// names cased/suffixed, the strip-prefix cross product and 60k random
// multi-scalar strings — agree on all of them. Two classes needed correcting
// first, and both are pinned in `branch-leaf-naming.test.ts` so removing the
// correction turns a test red:
//
// 1. `humanizeBranchSlug` and an ASTRAL first character (908 divergences, one
//    class). The twin uppercased `joined.charAt(0)` — a UTF-16 code UNIT — so a
//    lone high surrogate came back unchanged and `𐐨` stayed `𐐨`; the core
//    uppercases the scalar and answers `𐐀`. The fallback follows the CORE
//    because the core is already what both bound surfaces ship, and the twin's
//    answer was simply a JS quirk that cannot capitalise an astral leaf at all.
// 2. `sanitizeBranchSlug`'s `maxWords` outside `isDispatchableWordCap`. The
//    adapter reads it with serde `as_u64`, which answers None for a negative or
//    fractional cap and silently applies the default 4 where the twin sliced;
//    above 2^32 the two cores then disagree with EACH OTHER, because wasm32
//    truncates `as usize` (4294967296 → 0 words → `''`) and napi does not. Those
//    caps are answered from the local body instead of crossing.
//
// Each fallback is computed EAGERLY, before the dispatch: the types say string,
// but a branch leaf also arrives from persisted state and off the wire, and a
// non-string must throw the twin's TypeError on both paths rather than have the
// encoder ship it and Rust answer `""` for it.
import { DispatchPayloadError } from './dispatch-payload-codec'
import { MARINE_CREATURES } from './marine-creatures'
import { tryOrcaDispatch } from './orca-dispatch-seam'
import { MAX_BRANCH_NAME_WORDS } from './branch-name-from-work'

const BRANCH_NAME_FROM_WORK = 'branch-name-from-work'

const CREATURE_NAMES_LOWER = new Set(MARINE_CREATURES.map((name) => name.toLowerCase()))

/** The window in which the adapter's `as_u64` read means the same thing on
 *  wasm32 and on 64-bit napi. `-0` is excluded because the codec rejects it. */
function isDispatchableWordCap(maxWords: number): boolean {
  return (
    Number.isInteger(maxWords) &&
    !Object.is(maxWords, -0) &&
    maxWords >= 0 &&
    maxWords <= 4_294_967_295
  )
}

/** The deleted twin's body, verbatim over the kept creature table. */
function legacyIsAutoGeneratedCreatureBranchName(branchLeaf: string): boolean {
  const normalized = branchLeaf.trim().toLowerCase()
  if (!normalized) {
    return false
  }
  // Collision suffixes (`-2`, `-3`, …) are appended at creation; strip one
  // before checking membership so numbered creatures still qualify.
  return CREATURE_NAMES_LOWER.has(normalized.replace(/-\d+$/, ''))
}

/** The deleted twin's body, verbatim over the kept word cap. */
function legacySanitizeBranchSlug(raw: string, maxWords = MAX_BRANCH_NAME_WORDS): string {
  const words = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .split('-')
    .filter(Boolean)
  if (words.length === 0) {
    return ''
  }
  return words.slice(0, maxWords).join('-')
}

/** The deleted twin's body; `Infinity` is its uncapped normalisation. */
function legacyStripConfiguredBranchPrefix(
  slug: string,
  prefix: string | null | undefined
): string {
  if (!prefix) {
    return slug
  }
  const prefixSlug = legacySanitizeBranchSlug(prefix, Number.POSITIVE_INFINITY)
  if (!prefixSlug) {
    return slug
  }
  if (slug === prefixSlug) {
    return ''
  }
  return slug.startsWith(`${prefixSlug}-`) ? slug.slice(prefixSlug.length + 1) : slug
}

/** The deleted twin's body, with its UTF-16 `charAt(0)` corrected to the first
 *  code POINT so an astral leaf capitalises the way the core does. */
function legacyHumanizeBranchSlug(slug: string): string {
  const joined = slug.split('-').filter(Boolean).join(' ')
  if (!joined) {
    return ''
  }
  const first = String.fromCodePoint(joined.codePointAt(0) ?? 0)
  return first.toUpperCase() + joined.slice(first.length)
}

/** `null` = the seam is unbound, or the payload cannot cross — answer locally.
 *  Unambiguous: all four arms answer a bool or a string, never null.
 *  Why the catch: a branch leaf reaches these off the wire (a hosted provider's
 *  JSON `"\ud800"`, a relay mirror) and raw model stdout reaches
 *  `sanitizeBranchSlug`, so an unpaired UTF-16 surrogate is reachable and the
 *  codec refuses to encode it. The twin answered those without crossing
 *  anything, so the fallback does too; a DispatchCoreError still propagates. */
function dispatchBranchName(fn: string, input: unknown, root: string): unknown {
  try {
    return tryOrcaDispatch(BRANCH_NAME_FROM_WORK, fn, input, {
      root,
      undefinedProperties: 'omit'
    })
  } catch (error) {
    if (error instanceof DispatchPayloadError) {
      return null
    }
    throw error
  }
}

/**
 * True when `branchLeaf` (the segment after any `prefix/`) is an Orca
 * auto-generated creature name, e.g. `Nautilus` or `Octopus-2`. The eligibility
 * gate for auto-rename, so it only ever overwrites a name Orca itself picked.
 */
export function isAutoGeneratedCreatureBranchName(branchLeaf: string): boolean {
  const fallback = legacyIsAutoGeneratedCreatureBranchName(branchLeaf)
  const answer = dispatchBranchName('isAutoGeneratedCreatureBranchName', branchLeaf, 'branchLeaf')
  return answer === null ? fallback : (answer as boolean)
}

/**
 * Turn raw model output into a safe, short kebab-case branch leaf. `''` when
 * nothing usable remains, which callers treat as "skip the rename".
 */
export function sanitizeBranchSlug(raw: string, maxWords?: number): string {
  const fallback = legacySanitizeBranchSlug(raw, maxWords)
  if (maxWords !== undefined && !isDispatchableWordCap(maxWords)) {
    return fallback
  }
  // An absent `maxWords` key IS the Rust `None` that applies the port's own
  // MAX_BRANCH_NAME_WORDS default, hence `undefinedProperties: 'omit'`.
  const answer = dispatchBranchName('sanitizeBranchSlug', { raw, maxWords }, 'sanitizeBranchSlug')
  return answer === null ? fallback : (answer as string)
}

/**
 * Drop a leading prefix segment the generation model prepended — with a
 * `tmchow/` branch prefix the model emits `tmchow/worktree-spinner`, which the
 * slug folds to `tmchow-worktree-spinner` and would re-prefix to
 * `tmchow/tmchow-…`. Strips only when the leading segment matches the
 * *configured* prefix, so a name that merely starts with a real word survives;
 * prefix-only output yields `''` so the caller skips the rename.
 */
export function stripConfiguredBranchPrefix(
  slug: string,
  prefix: string | null | undefined
): string {
  const fallback = legacyStripConfiguredBranchPrefix(slug, prefix)
  const answer = dispatchBranchName(
    'stripConfiguredBranchPrefix',
    { slug, prefix: prefix ?? null },
    'stripConfiguredBranchPrefix'
  )
  return answer === null ? fallback : (answer as string)
}

/**
 * Turn a branch slug into a readable workspace display label, e.g.
 * `supported-models-list` → `Supported models list`.
 */
export function humanizeBranchSlug(slug: string): string {
  const fallback = legacyHumanizeBranchSlug(slug)
  const answer = dispatchBranchName('humanizeBranchSlug', slug, 'slug')
  return answer === null ? fallback : (answer as string)
}
