// The 4 branch-name string helpers (isAutoGeneratedCreatureBranchName,
// sanitizeBranchSlug, stripConfiguredBranchPrefix, humanizeBranchSlug) moved to
// the Rust branch-name-from-work core (orca-core) and are reached through ONE
// shim on the shared dispatch seam, `src/shared/branch-leaf-naming.ts`, because
// main and the renderer both call them. This file keeps the types and the word
// cap they need, and `buildBranchNamePrompt`.
//
// buildBranchNamePrompt stays in TS on purpose: it is prompt COPY, and it is the
// last live TS-vs-Rust comparison the `branch-name-from-work` parity module has
// (the other four now compare the wasm core against itself), so cutting it over
// would leave prompt-copy drift with nothing watching it.

// Why: post-generation sanitization still bounds the leaf so a long model dump
// cannot become an unreadable branch. The *prompt* stays general — users can
// override naming style via Source Control AI instructions / templates.
export const MAX_BRANCH_NAME_WORDS = 4

export type BranchNameWorkContext = {
  /** The user's first prompt to the agent in this workspace. */
  firstPrompt: string
  /** The agent's first response, when it has already arrived. Optional because
   *  the rename fires as soon as work begins, before a reply may exist. */
  assistantMessage?: string
}

/**
 * Build the text-generation prompt that asks the configured agent to name the
 * work. Kept in shared so the prompt is identical across local and SSH targets.
 *
 * Why: the shipped default stays general. Naming style is left open so users
 * who override via Source Control AI instructions / the branch-name command
 * template are not fighting a rigid built-in rule list. Git-safety (kebab,
 * length) is enforced after generation by sanitizeBranchSlug.
 */
export function buildBranchNamePrompt(context: BranchNameWorkContext, customPrompt = ''): string {
  const sections: string[] = []
  const prompt = customPrompt.trim()
  // Why: when the user supplies naming guidance, lead with it so their
  // override owns style rather than sitting under a prescriptive default.
  if (prompt) {
    sections.push(prompt, '')
  }
  sections.push(
    prompt
      ? 'Generate a git branch name that summarizes the coding task described below.'
      : 'Generate a short git branch name that summarizes the coding task described below.',
    'Output ONLY the branch name on a single line, nothing else.',
    ''
  )
  sections.push('User request:', context.firstPrompt.trim())
  const assistant = context.assistantMessage?.trim()
  if (assistant) {
    sections.push('', "Agent's initial response:", assistant)
  }
  return sections.join('\n')
}
