// The branch-name twin's four helper test suites, restored from the commit that
// deleted them (d1d7114fdd^) and moved onto the seam shim. Every case runs TWICE
// — seam unbound (the renderer before wasm init, the preload, mobile, a
// Playwright spec) and bound to the wasm core (main/cli via napi, the relay via
// initSync) — because the slug is renamed onto a real branch and the humanized
// label is persisted as the workspace display name.
import { afterEach, describe, expect, it } from 'vitest'
import {
  humanizeBranchSlug,
  isAutoGeneratedCreatureBranchName,
  sanitizeBranchSlug,
  stripConfiguredBranchPrefix
} from './branch-leaf-naming'
import { setOrcaDispatchBinding } from './orca-dispatch-seam'
import { orcaDispatch } from '../relay/wasm/orca_git_wasm.js'

function bindWasm(): void {
  setOrcaDispatchBinding((module, fn, inputJson) => orcaDispatch(module, fn, inputJson))
}

/** Run `call` unbound and bound; assert both equal `expected`. */
function bothStates<T>(call: () => T, expected: T): void {
  setOrcaDispatchBinding(null)
  expect(call()).toEqual(expected)
  bindWasm()
  expect(call()).toEqual(expected)
}

/** The raw core answer, with no shim guard in the way. */
function rawCore(fn: string, input: unknown): unknown {
  return JSON.parse(orcaDispatch('branch-name-from-work', fn, JSON.stringify(input)))
}

afterEach(() => setOrcaDispatchBinding(null))

describe('sanitizeBranchSlug', () => {
  it('lowercases and kebab-cases free-form model output', () => {
    bothStates(() => sanitizeBranchSlug('Fix the auth bug'), 'fix-the-auth-bug')
  })

  it('caps at four words', () => {
    bothStates(
      () => sanitizeBranchSlug('add dark mode toggle to settings page'),
      'add-dark-mode-toggle'
    )
  })

  it('honors a custom word cap', () => {
    bothStates(() => sanitizeBranchSlug('add dark mode toggle', 2), 'add-dark')
  })

  it('collapses punctuation, quotes, and slashes into single hyphens', () => {
    bothStates(() => sanitizeBranchSlug('"feat/login_flow!!"'), 'feat-login-flow')
  })

  it('returns empty string when nothing usable remains', () => {
    bothStates(() => sanitizeBranchSlug('   !!! ___ '), '')
    bothStates(() => sanitizeBranchSlug(''), '')
  })
})

// The measured guard: serde `as_u64` answers None for a negative or fractional
// cap and applies the port's default 4, and above 2^32 the two shipped cores
// disagree with each other (wasm32 truncates `as usize`, napi does not). Each
// case asserts the twin's answer AND that the raw core would have differed, so
// the day the adapter learns to read these the second half turns red and the
// guard is re-derived instead of outliving its reason.
describe('sanitizeBranchSlug word caps the core cannot read', () => {
  it('slices from the end for a negative cap, where the core applies its default', () => {
    bothStates(() => sanitizeBranchSlug('fix the auth bug', -1), 'fix-the-auth')
    expect(rawCore('sanitizeBranchSlug', { raw: 'fix the auth bug', maxWords: -1 })).toBe(
      'fix-the-auth-bug'
    )
  })

  it('truncates a fractional cap toward zero, where the core applies its default', () => {
    bothStates(() => sanitizeBranchSlug('fix the auth bug', 2.5), 'fix-the')
    bothStates(() => sanitizeBranchSlug('fix the auth bug', 0.5), '')
    expect(rawCore('sanitizeBranchSlug', { raw: 'fix the auth bug', maxWords: 2.5 })).toBe(
      'fix-the-auth-bug'
    )
  })

  it('keeps every word above 2^32, where wasm32 truncates the cast to zero', () => {
    bothStates(() => sanitizeBranchSlug('a b c d e f', 4_294_967_296), 'a-b-c-d-e-f')
    expect(
      rawCore('sanitizeBranchSlug', {
        raw: 'a b c d e f',
        maxWords: 4_294_967_296
      })
    ).toBe('')
  })

  it('answers non-finite and -0 caps locally rather than failing the encode', () => {
    bothStates(() => sanitizeBranchSlug('a b c d e f', Number.POSITIVE_INFINITY), 'a-b-c-d-e-f')
    bothStates(() => sanitizeBranchSlug('a b c d e f', Number.NaN), '')
    bothStates(() => sanitizeBranchSlug('a b c d e f', -0), '')
  })

  it('still dispatches the whole in-window range', () => {
    for (const maxWords of [0, 1, 4, 6, 4_294_967_295]) {
      const core = rawCore('sanitizeBranchSlug', {
        raw: 'a b c d e f',
        maxWords
      }) as string
      bothStates(() => sanitizeBranchSlug('a b c d e f', maxWords), core)
    }
  })
})

describe('isAutoGeneratedCreatureBranchName', () => {
  it('matches creature names case-insensitively', () => {
    bothStates(() => isAutoGeneratedCreatureBranchName('Nautilus'), true)
    bothStates(() => isAutoGeneratedCreatureBranchName('octopus'), true)
  })

  it('matches numbered collision variants', () => {
    bothStates(() => isAutoGeneratedCreatureBranchName('Nautilus-2'), true)
    bothStates(() => isAutoGeneratedCreatureBranchName('Seahorse-17'), true)
  })

  it('rejects user-chosen and work-derived names', () => {
    bothStates(() => isAutoGeneratedCreatureBranchName('fix-auth-bug'), false)
    bothStates(() => isAutoGeneratedCreatureBranchName('my-feature'), false)
    bothStates(() => isAutoGeneratedCreatureBranchName(''), false)
  })
})

describe('stripConfiguredBranchPrefix', () => {
  it('strips a leaked configured prefix', () => {
    bothStates(
      () => stripConfiguredBranchPrefix('tmchow-worktree-creation-spinner', 'tmchow'),
      'worktree-creation-spinner'
    )
    bothStates(() => stripConfiguredBranchPrefix('my-team-add-logout', 'my-team'), 'add-logout')
    bothStates(() => stripConfiguredBranchPrefix('jane-doe-fix-auth', 'Jane.Doe'), 'fix-auth')
  })

  it('leaves content and absent prefixes untouched', () => {
    bothStates(
      () => stripConfiguredBranchPrefix('add-logout-button', 'tmchow'),
      'add-logout-button'
    )
    bothStates(() => stripConfiguredBranchPrefix('tmchow-fix-auth', null), 'tmchow-fix-auth')
    bothStates(() => stripConfiguredBranchPrefix('tmchow-fix-auth', undefined), 'tmchow-fix-auth')
    bothStates(() => stripConfiguredBranchPrefix('tmchow-fix-auth', ''), 'tmchow-fix-auth')
  })

  it('returns empty for prefix-only output so the caller skips the rename', () => {
    bothStates(() => stripConfiguredBranchPrefix('tmchow', 'tmchow'), '')
    bothStates(() => stripConfiguredBranchPrefix('tmchow-fix-auth', 'tmchow'), 'fix-auth')
  })
})

describe('humanizeBranchSlug', () => {
  it('turns kebab into a readable label', () => {
    bothStates(() => humanizeBranchSlug('supported-models-list'), 'Supported models list')
    bothStates(() => humanizeBranchSlug('fix-auth'), 'Fix auth')
  })

  it('returns empty for an empty slug', () => {
    bothStates(() => humanizeBranchSlug(''), '')
  })

  // The measured correction: the twin uppercased `joined.charAt(0)`, a UTF-16
  // code UNIT, so a lone high surrogate came back unchanged and an astral leaf
  // was never capitalised. The core uppercases the scalar, and the core is what
  // both bound surfaces already ship — so the fallback follows it, and this row
  // turns red if the fallback is reverted to `charAt(0)`.
  it('capitalises an astral first character the way the core does', () => {
    bothStates(() => humanizeBranchSlug('\u{10428}eseret-branch'), '\u{10400}eseret branch')
    expect('\u{10428}eseret branch'.charAt(0).toUpperCase()).toBe(
      '\u{10428}eseret branch'.charAt(0)
    )
  })
})

describe('the dispatch boundary', () => {
  it('answers locally when a lone surrogate cannot be encoded', () => {
    bindWasm()
    // Reachable off the wire: a hosted provider's JSON `"\ud800"` survives
    // JSON.parse and reaches the renderer's draft-title path as a branch leaf.
    expect(humanizeBranchSlug('lone-\ud800-tail')).toBe('Lone \ud800 tail')
    expect(sanitizeBranchSlug('Fix \ud800 bug')).toBe('fix-bug')
    expect(isAutoGeneratedCreatureBranchName('nautilus\ud800')).toBe(false)
    expect(stripConfiguredBranchPrefix('tmchow-fix', 'tm\ud800chow')).toBe('tmchow-fix')
  })

  it('propagates a core failure rather than folding it into an answer', () => {
    setOrcaDispatchBinding(() => '{"__dispatch_error__":"unknown module"}')
    expect(() => humanizeBranchSlug('fix-auth')).toThrow(/failed in the Rust core/)
  })

  // The fallbacks run BEFORE the dispatch so a non-string — the types say
  // string, but a display name also arrives from persisted state — throws the
  // twin's TypeError on both paths instead of the core reading it as `""`.
  it('throws the twin TypeError for a non-string on both paths', () => {
    for (const bind of [() => setOrcaDispatchBinding(null), bindWasm]) {
      bind()
      const notAString = 7 as unknown as string
      expect(() => humanizeBranchSlug(notAString)).toThrow(TypeError)
      expect(() => sanitizeBranchSlug(notAString)).toThrow(TypeError)
      expect(() => isAutoGeneratedCreatureBranchName(notAString)).toThrow(TypeError)
      expect(() => stripConfiguredBranchPrefix(notAString, 'tmchow')).toThrow(TypeError)
    }
  })
})
