//! `String.prototype.normalize('NFC')` for the zero-dependency core.
//!
//! Ports exist here only because a twin needs them: `cross-platform-path.ts`
//! folds every path comparison key through NFC, because macOS hands Orca
//! decomposed (NFD) names while agents record the same directory composed (NFC),
//! and a non-ASCII workspace otherwise never matches its own sessions (#10832).
//! Rust has no NFC in `std` and the crate takes no dependencies, so the
//! canonical data lives in `unicode_nfc_data.rs`, generated by
//! `config/scripts/generate-unicode-nfc-tables.mjs` out of the same V8/ICU that
//! runs the twin.
//!
//! The algorithm is UAX #15: canonical decomposition, canonical ordering, then
//! canonical composition. Hangul is algorithmic (UAX #15, 3.12) rather than
//! tabulated — 11172 syllables would otherwise dominate the data.

use crate::unicode_nfc_data::{COMBINING_CLASSES, COMPOSITIONS, DECOMPOSITIONS};
use crate::MAX_PREALLOC_HINT;
use std::borrow::Cow;
use std::cmp::Ordering;

const HANGUL_S_BASE: u32 = 0xAC00;
const HANGUL_L_BASE: u32 = 0x1100;
const HANGUL_V_BASE: u32 = 0x1161;
/// One *below* the first trailing jamo, so `T_BASE + 0` means "no trailing jamo".
const HANGUL_T_BASE: u32 = 0x11A7;
const HANGUL_L_COUNT: u32 = 19;
const HANGUL_V_COUNT: u32 = 21;
const HANGUL_T_COUNT: u32 = 28;
const HANGUL_N_COUNT: u32 = HANGUL_V_COUNT * HANGUL_T_COUNT;
const HANGUL_S_COUNT: u32 = HANGUL_L_COUNT * HANGUL_N_COUNT;

/// Canonical combining class; 0 for every starter.
fn combining_class(value: char) -> u8 {
    let found = COMBINING_CLASSES.binary_search_by(|(start, end, _)| {
        if *start > value {
            Ordering::Greater
        } else if *end < value {
            Ordering::Less
        } else {
            Ordering::Equal
        }
    });
    match found {
        Ok(index) => COMBINING_CLASSES.get(index).map_or(0, |(_, _, ccc)| *ccc),
        Err(_) => 0,
    }
}

/// Full canonical decomposition, already canonically ordered.
fn canonical_decomposition(value: char) -> Option<&'static str> {
    let index = DECOMPOSITIONS
        .binary_search_by(|(key, _)| key.cmp(&value))
        .ok()?;
    DECOMPOSITIONS.get(index).map(|(_, decomposed)| *decomposed)
}

fn primary_composite(first: char, second: char) -> Option<char> {
    let index = COMPOSITIONS
        .binary_search_by(|(a, b, _)| a.cmp(&first).then_with(|| b.cmp(&second)))
        .ok()?;
    COMPOSITIONS.get(index).map(|(_, _, composed)| *composed)
}

fn hangul_syllable_parts(value: char) -> Option<(char, char, Option<char>)> {
    let syllable = u32::from(value).checked_sub(HANGUL_S_BASE)?;
    if syllable >= HANGUL_S_COUNT {
        return None;
    }
    let lead = char::from_u32(HANGUL_L_BASE + syllable / HANGUL_N_COUNT)?;
    let vowel = char::from_u32(HANGUL_V_BASE + (syllable % HANGUL_N_COUNT) / HANGUL_T_COUNT)?;
    let trail_index = syllable % HANGUL_T_COUNT;
    let trail = if trail_index == 0 {
        None
    } else {
        Some(char::from_u32(HANGUL_T_BASE + trail_index)?)
    };
    Some((lead, vowel, trail))
}

fn compose_hangul(first: char, second: char) -> Option<char> {
    let a = u32::from(first);
    let b = u32::from(second);
    if let Some(lead) = a.checked_sub(HANGUL_L_BASE) {
        if let Some(vowel) = b.checked_sub(HANGUL_V_BASE) {
            if lead < HANGUL_L_COUNT && vowel < HANGUL_V_COUNT {
                return char::from_u32(
                    HANGUL_S_BASE + (lead * HANGUL_V_COUNT + vowel) * HANGUL_T_COUNT,
                );
            }
        }
    }
    let syllable = a.checked_sub(HANGUL_S_BASE)?;
    let trail = b.checked_sub(HANGUL_T_BASE)?;
    let is_lv_syllable = syllable < HANGUL_S_COUNT && syllable % HANGUL_T_COUNT == 0;
    if is_lv_syllable && (1..HANGUL_T_COUNT).contains(&trail) {
        return char::from_u32(a + trail);
    }
    None
}

/// Cheap sufficient test for "NFC would return this unchanged". Conservative in
/// the safe direction: a `false` only costs the slow path, which answers the
/// same string.
fn is_certainly_nfc(value: &str) -> bool {
    if value.is_ascii() {
        return true;
    }
    let mut previous: Option<char> = None;
    for ch in value.chars() {
        if canonical_decomposition(ch).is_some() || combining_class(ch) != 0 {
            return false;
        }
        if hangul_syllable_parts(ch).is_some() {
            return false;
        }
        if previous.and_then(|p| primary_composite(p, ch)).is_some()
            || previous.and_then(|p| compose_hangul(p, ch)).is_some()
        {
            return false;
        }
        previous = Some(ch);
    }
    true
}

/// UAX #15 canonical decomposition (D68) followed by canonical ordering (D109).
fn decompose_and_order(value: &str) -> Vec<char> {
    let mut buffer: Vec<char> = Vec::with_capacity(value.len().min(MAX_PREALLOC_HINT));
    for ch in value.chars() {
        if let Some((lead, vowel, trail)) = hangul_syllable_parts(ch) {
            buffer.push(lead);
            buffer.push(vowel);
            if let Some(trail) = trail {
                buffer.push(trail);
            }
        } else if let Some(decomposed) = canonical_decomposition(ch) {
            // Table entries are already fully expanded and canonically ordered,
            // so one pass suffices — no recursion for Trust to bound.
            buffer.extend(decomposed.chars());
        } else {
            buffer.push(ch);
        }
    }

    // Canonical ordering sorts each run of non-starters by class, stably. Rust's
    // `sort_by_key` IS stable, so this is the bubble sort of D109 without the
    // hand-rolled index arithmetic.
    let mut start = 0;
    while start < buffer.len() {
        if buffer.get(start).is_none_or(|ch| combining_class(*ch) == 0) {
            start += 1;
            continue;
        }
        let mut end = start;
        while buffer.get(end).is_some_and(|ch| combining_class(*ch) != 0) {
            end += 1;
        }
        if let Some(run) = buffer.get_mut(start..end) {
            run.sort_by_key(|ch| combining_class(*ch));
        }
        start = end.max(start + 1);
    }
    buffer
}

/// UAX #15 canonical composition (D117): fold each character into the last
/// starter unless it is blocked from it.
fn compose(decomposed: Vec<char>) -> String {
    let mut out: Vec<char> = Vec::with_capacity(decomposed.len().min(MAX_PREALLOC_HINT));
    // Index in `out` of the starter a following character may compose with, plus
    // the class of the last character accepted after it. `None` means the next
    // character sits directly on the starter, so nothing can block it.
    let mut starter: Option<usize> = None;
    let mut last_class: Option<u8> = None;

    for ch in decomposed {
        let class = combining_class(ch);
        let composed = match (starter, last_class) {
            // Blocked when something between the starter and `ch` has a class at
            // or above `ch`'s own (the run is ordered, so the last one is the max).
            (Some(index), blocker) if blocker.is_none_or(|previous| previous < class) => out
                .get(index)
                .copied()
                .and_then(|first| {
                    primary_composite(first, ch).or_else(|| compose_hangul(first, ch))
                })
                .map(|composite| (index, composite)),
            _ => None,
        };
        if let Some((index, composite)) = composed {
            if let Some(slot) = out.get_mut(index) {
                *slot = composite;
                continue;
            }
        }
        if class == 0 {
            starter = Some(out.len());
            last_class = None;
        } else {
            last_class = Some(class);
        }
        out.push(ch);
    }

    let mut text = String::with_capacity(out.len().min(MAX_PREALLOC_HINT));
    text.extend(out);
    text
}

/// Normalization Form C, matching `String.prototype.normalize('NFC')`.
pub fn to_nfc(value: &str) -> Cow<'_, str> {
    if is_certainly_nfc(value) {
        return Cow::Borrowed(value);
    }
    Cow::Owned(compose(decompose_and_order(value)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn leaves_ascii_and_already_composed_text_alone() {
        assert_eq!(to_nfc("/repo/app/src/index.ts"), "/repo/app/src/index.ts");
        assert_eq!(to_nfc(""), "");
        // Already NFC: no decomposition, nothing to compose.
        assert_eq!(to_nfc("/srv/café"), "/srv/café");
        // A borrowed answer is the fast path; the value must still be right.
        assert!(matches!(to_nfc("/plain/ascii"), Cow::Borrowed(_)));
    }

    #[test]
    fn composes_latin_accents_from_their_decomposed_form() {
        assert_eq!(to_nfc("cafe\u{301}"), "café");
        assert_eq!(to_nfc("A\u{300}"), "\u{C0}");
        // Two marks, already in canonical order: s + dot-below + dot-above.
        assert_eq!(to_nfc("s\u{323}\u{307}"), "\u{1E69}");
        // Reversed input must be reordered before composing (class 220 < 230).
        assert_eq!(to_nfc("s\u{307}\u{323}"), "\u{1E69}");
    }

    #[test]
    fn composes_hangul_jamo_algorithmically() {
        // 프로젝트 as L/V(/T) jamo.
        let jamo = "\u{1111}\u{1173}\u{1105}\u{1169}\u{110C}\u{1166}\u{11A8}\u{1110}\u{1173}";
        assert_eq!(to_nfc(jamo), "프로젝트");
        // A trailing jamo joins the LV syllable it follows.
        assert_eq!(to_nfc("\u{AC00}\u{11A8}"), "\u{AC01}");
    }

    #[test]
    fn respects_composition_exclusions_and_blocking() {
        // U+0344 is a full-composition exclusion: NFC keeps the two marks.
        assert_eq!(to_nfc("\u{0344}"), "\u{0308}\u{0301}");
        // U+2126 OHM SIGN is a singleton exclusion: NFC maps it to Greek omega
        // and never composes back.
        assert_eq!(to_nfc("\u{2126}"), "\u{3A9}");
        // The grave composes into the 'e'; the acute then has no composite with
        // è, so it stays a separate mark rather than displacing the grave.
        assert_eq!(to_nfc("e\u{300}\u{301}"), "\u{E8}\u{301}");
    }

    #[test]
    fn combining_marks_keep_canonical_order_when_nothing_composes() {
        // Classes 220 then 230; a 230-before-220 input must come back reordered.
        assert_eq!(to_nfc("\u{25CC}\u{307}\u{323}"), "\u{25CC}\u{323}\u{307}");
    }
}
