// TS dispatch for the branch-name-from-work parity module. The shared TS impl
// was DELETED (`src/shared/branch-name-from-work.ts` keeps only
// `MAX_BRANCH_NAME_WORDS` and the `BranchNameWorkContext` type) — every surface
// now reaches `orca_core::branch_name_from_work` through
// `src/shared/branch-leaf-naming.ts` on the orca-dispatch seam.
//
// Like the wsl-paths, worktree-id and stable-pane-id adapters, this drives the
// SHIM rather than the wasm oracle, and the harness keeps a real TS-vs-Rust
// differential instead of degenerating to wasm-vs-binary:
// config/vitest.parity.config.ts installs no setup file, so the seam is unbound
// here and the shim answers from its `parity` fallback — which is exactly the
// deleted body, and exactly the code main/renderer/relay run before (or
// without) a binding.
//
// That is what replaced `buildBranchNamePrompt`'s old reason for staying in TS.
// It was kept as "the module's last live TS-vs-Rust drift check" while the other
// four ran through the oracle; routing all five through the shim restores that
// check for the whole module, on the production code path.
import {
  buildBranchNamePrompt,
  humanizeBranchSlug,
  isAutoGeneratedCreatureBranchName,
  sanitizeBranchSlug,
  stripConfiguredBranchPrefix
} from '../../../src/shared/branch-leaf-naming'
import type { BranchNameWorkContext } from '../../../src/shared/branch-name-from-work'

export function dispatch(fn: string, input: unknown): unknown {
  switch (fn) {
    case 'isAutoGeneratedCreatureBranchName':
      return isAutoGeneratedCreatureBranchName(input as string)
    case 'sanitizeBranchSlug': {
      const { raw, maxWords } = input as { raw: string; maxWords?: number }
      return sanitizeBranchSlug(raw, maxWords)
    }
    case 'humanizeBranchSlug':
      return humanizeBranchSlug(input as string)
    case 'stripConfiguredBranchPrefix': {
      const { slug, prefix } = input as { slug: string; prefix?: string | null }
      return stripConfiguredBranchPrefix(slug, prefix)
    }
    case 'buildBranchNamePrompt': {
      const { context, customPrompt } = input as {
        context: BranchNameWorkContext
        customPrompt?: string
      }
      // The twin's default parameter, not an empty string the caller passed.
      return customPrompt === undefined
        ? buildBranchNamePrompt(context)
        : buildBranchNamePrompt(context, customPrompt)
    }
    default:
      throw new Error(`unknown function ${fn}`)
  }
}
