// Pre-ready contract rows (rule + machinery:
// ./shim-pre-ready-contract-harness.ts) for the git and provider surface:
// push-target shape, upstream reconciliation, publish targets, base refs,
// branch naming, GitHub merge methods, GitLab pipeline checks, commit-message
// host keys, task query/providers, Linear URLs, and the fleet exception queue.
import { legacyBaseRefSearchResults } from './base-ref-search-result'
import {
  buildBranchNamePrompt,
  humanizeBranchSlug,
  isAutoGeneratedCreatureBranchName,
  sanitizeBranchSlug,
  stripConfiguredBranchPrefix
} from '../../../../shared/branch-leaf-naming'
import { getCommitMessageModelDiscoveryHostKeyForScope } from './commit-message-host-key'
import { collapseExceptionsByTask, unwiredExceptionSources } from './fleet-exception-queue'
import { getPublishTargetDisplayName } from './git-publish-target-status'
import { assertGitPushTargetShape } from '../../../../shared/git-push-target-shape'
import {
  isBehindOnlyUpstream,
  shouldForcePushWithLeaseForUpstream
} from '../../../../shared/git-upstream-reconciliation'
import { resolveGitHubPRMergeMethods } from './github-pr-merge-methods'
import { gitLabPipelineJobsToPRChecks } from './gitlab-pipeline-checks'
import { normalizeHostedReviewBaseRef } from './hosted-review-refs'
import {
  buildLinearPersonalApiKeySettingsUrl,
  buildLinearTeamUrl,
  buildLinearWorkspaceApiSettingsUrl
} from '../../../../shared/linear-app-urls'
import { filterAvailableTaskProviders, resolveVisibleTaskProvider } from './task-providers'
import { parseTaskQuery, withQualifier } from './task-query'
import { runShimPreReadyContractSuite } from './shim-pre-ready-contract-harness'
import type { PreReadyCase } from './shim-pre-ready-contract-harness'

const CASES: PreReadyCase[] = [
  {
    name: 'git-publish-target-status.getPublishTargetDisplayName',
    call: () => getPublishTargetDisplayName({ remoteName: 'upstream', branchName: 'feature/foo' }),
    contract: {
      kind: 'parity',
      why: 'the fallback rejoins remote/branch inline — the twin did nothing else, for any input'
    }
  },
  // All four branches of the one exported function, because the fallback
  // reproduces the mapping rather than a constant: a row per branch is what
  // stops it drifting from the core. Parity is mandatory here — the result is a
  // CACHE KEY into persisted settings (discoveredModelsByAgentByHost /
  // selectedModelByAgentByHost), and source-control-ai.ts reads an absent key as
  // LOCAL, so a sentinel would come back as a wrong host key instead of a signal.
  {
    name: 'commit-message-host-key.forScope(undefined)',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope(undefined),
    contract: { kind: 'parity', why: "an undefined scope is 'unknown' in both states" }
  },
  {
    name: 'commit-message-host-key.forScope(null)',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope(null),
    contract: { kind: 'parity', why: "no scope is the 'local' constant the twin returned" }
  },
  {
    name: 'commit-message-host-key.forScope("runtime:env-1")',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope('runtime:env-1'),
    contract: { kind: 'parity', why: 'a runtime scope passes through unchanged in both states' }
  },
  {
    name: 'commit-message-host-key.forScope("conn-1")',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope('conn-1'),
    contract: {
      kind: 'parity',
      why: 'the fallback re-prefixes ssh: inline — the twin did nothing else, for any connection id'
    }
  },
  {
    name: 'github-pr-merge-methods.resolveGitHubPRMergeMethods(null)',
    call: () => resolveGitHubPRMergeMethods(null),
    contract: { kind: 'parity', why: 'no settings is exactly the constant the twin returned' }
  },
  {
    name: 'gitlab-pipeline-checks.gitLabPipelineJobsToPRChecks',
    call: () => gitLabPipelineJobsToPRChecks([]),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'ChecksPanel.fetchGitLabDetails skips the poll update, holds the spinner while pending (the ready edge refetches), and hides ChecksList once availability is terminal — an empty list reads as "No checks configured"'
    }
  },
  {
    name: 'hosted-review-refs.normalizeHostedReviewBaseRef("refs/heads/main")',
    call: () => normalizeHostedReviewBaseRef('refs/heads/main'),
    contract: {
      kind: 'divergence',
      consequence: 'the unstripped ref never equals a branch name, so base-ref comparisons miss'
    }
  },
  {
    name: 'task-query.parseTaskQuery("is:open author:me")',
    call: () => parseTaskQuery('is:open author:me'),
    contract: {
      kind: 'divergence',
      consequence:
        'an empty parse is indistinguishable from a query with no filters — TaskPage shows everything'
    }
  },
  {
    name: 'task-query.withQualifier',
    call: () => withQualifier('', 'state', 'open'),
    contract: {
      kind: 'divergence',
      consequence: 'the filter click silently no-ops (the query is returned unchanged)'
    }
  },
  {
    name: 'task-providers.filterAvailableTaskProviders',
    call: () =>
      filterAvailableTaskProviders(['github', 'gitlab', 'linear', 'jira'], {
        gitlabInstalled: false,
        linearConnected: false
      }),
    contract: {
      kind: 'divergence',
      consequence: 'unavailable providers stay in the UI — the whole point of the filter'
    }
  },
  {
    name: 'task-providers.resolveVisibleTaskProvider(hidden preference)',
    call: () => resolveVisibleTaskProvider('linear', ['github']),
    contract: { kind: 'divergence', consequence: 'resolves to a provider that is not visible' }
  },
  // All five are mandatory parity, not tidy: the slug is renamed onto a real
  // branch, the humanized label is persisted as the workspace display name, the
  // prompt is what an agent is spawned on, and `''`/`false` are already each
  // function's real answer, so no sentinel has anywhere to live. The four helper
  // fallbacks proved equal to both shipped cores over 16.1M differential
  // probes — see the shim header.
  {
    name: 'branch-leaf-naming.sanitizeBranchSlug',
    call: () => sanitizeBranchSlug('Fix The Bug!!'),
    contract: { kind: 'parity', why: 'the fallback re-runs the twin kebab-case body inline' }
  },
  {
    name: 'branch-leaf-naming.isAutoGeneratedCreatureBranchName',
    call: () => isAutoGeneratedCreatureBranchName('Nautilus-2'),
    contract: { kind: 'parity', why: 'the fallback looks up the kept MARINE_CREATURES table' }
  },
  {
    name: 'branch-leaf-naming.stripConfiguredBranchPrefix',
    call: () => stripConfiguredBranchPrefix('tmchow-fix-auth', 'Tmchow'),
    contract: { kind: 'parity', why: 'the fallback normalizes and strips the prefix inline' }
  },
  {
    name: 'branch-leaf-naming.humanizeBranchSlug(astral leaf)',
    call: () => humanizeBranchSlug('\u{10428}eseret-branch'),
    contract: {
      kind: 'parity',
      why: 'the fallback uppercases the first code POINT, as the core does — charAt(0) could not'
    }
  },
  {
    name: 'branch-leaf-naming.buildBranchNamePrompt',
    call: () =>
      buildBranchNamePrompt(
        { firstPrompt: '  Add a logout button  ', assistantMessage: '  Wiring it up.  ' },
        '  Prefer product nouns.  '
      ),
    contract: {
      kind: 'parity',
      why: "the fallback joins the twin's sections inline — settings' BUILT_IN_BRANCH_NAME_PROMPT is built at MODULE LOAD, so pre-ready is the only state that popover ever sees"
    }
  },
  {
    // Case 3: the twin strips `origin/`/`upstream/` only when a non-empty
    // remainder follows, so the answer depends on the input and no constant is
    // honest. List-shaped on purpose — a per-row null collapses to `[]`, which
    // the branch picker renders as "No matching branches".
    name: 'base-ref-search-result.legacyBaseRefSearchResults(["origin/main"])',
    call: () => legacyBaseRefSearchResults(['origin/main']),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'searchRuntimeRepoBaseRefDetails and the web preload repos.searchBaseRefDetails throw BaseRefDetailsUnavailableError, so the PR dialog shows "Branch discovery failed." and SmartWorkspaceNameField its branch-search failure line instead of an empty list'
    }
  },
  {
    name: 'git-push-target-shape.assertGitPushTargetShape(valid)',
    call: () => pushTargetOutcome({ remoteName: 'origin', branchName: 'feature/fix' }),
    contract: {
      kind: 'parity',
      why: 'an `asserts` fn has only throw/return, both real answers — the fallback is the twin body over the kept rule constants, so a valid target is never rejected while the seam is unbound'
    }
  },
  {
    name: 'git-push-target-shape.assertGitPushTargetShape(traversal remote)',
    call: () => pushTargetOutcome({ remoteName: 'foo/../bar', branchName: 'feature/fix' }),
    contract: {
      kind: 'parity',
      why: 'the rejecting direction, message included: this is the anti-traversal gate on a value replayed into `git push`, so pre-ready must not fail open'
    }
  },
  {
    name: 'git-push-target-shape.assertGitPushTargetShape(lone surrogate in branch)',
    call: () => pushTargetOutcome({ remoteName: 'origin', branchName: 'feat-\ud800' }),
    contract: {
      kind: 'parity',
      why: 'the codec refuses to encode it in BOTH states, so both take the fallback — the twin accepted it (check-ref-format is the next gate), and the reverted first attempt was exactly this accept turning into a reject naming the wrong field'
    }
  },
  // linear.app URL builders: parity is forced because every answer is handed to
  // window.api.shell.openUrl, and the global `linear.app/settings/…` URL and
  // buildLinearTeamUrl's null are both REAL answers (blank slug / blank key), so
  // neither can double as a signal — a pre-ready one opens the wrong workspace
  // or kills TaskPage's "open team in Linear" action for the session.
  {
    name: 'linear-app-urls.buildLinearTeamUrl(both keys)',
    call: () => buildLinearTeamUrl({ organizationUrlKey: 'acme inc', teamKey: 'A/B' }),
    contract: { kind: 'parity', why: 'the fallback percent-encodes both segments inline' }
  },
  {
    name: 'linear-app-urls.buildLinearTeamUrl(blank team key)',
    call: () => buildLinearTeamUrl({ organizationUrlKey: 'acme', teamKey: '  ' }),
    contract: {
      kind: 'parity',
      why: "null is the twin's real no-key answer, which TaskPage reads as 'this team has no link'"
    }
  },
  {
    name: 'linear-app-urls.buildLinearPersonalApiKeySettingsUrl(slug)',
    call: () => buildLinearPersonalApiKeySettingsUrl('acme inc'),
    contract: { kind: 'parity', why: 'the org-scoped page, not the global one, in both states' }
  },
  {
    name: 'linear-app-urls.buildLinearWorkspaceApiSettingsUrl(no slug)',
    call: () => buildLinearWorkspaceApiSettingsUrl('   '),
    contract: {
      kind: 'parity',
      why: 'the global URL is the answer for a blank slug — and only for a blank slug'
    }
  },
  {
    // Pins the trim SET: JS strips U+FEFF and keeps U+0085, Rust's
    // char::is_whitespace does the opposite, so a slug carrying either must
    // resolve identically on both paths.
    name: 'linear-app-urls.buildLinearWorkspaceApiSettingsUrl(BOM-wrapped slug)',
    call: () => buildLinearWorkspaceApiSettingsUrl('\u{FEFF}acme\u{FEFF}'),
    contract: {
      kind: 'parity',
      why: 'the ECMAScript trim set on both paths, not Unicode White_Space'
    }
  },
  // The ALab exceptions queue: parity, because the empty list a sentinel would
  // collapse to is the SILENT-FAILURE value here. ExceptionsQueue prints
  // "Nothing is waiting on you." for an empty list on a successful poll, so a
  // pre-ready [] tells a supervisor the fleet is clear while a gate is open.
  {
    name: 'fleet-exception-queue.collapseExceptionsByTask(retry storm + gate)',
    call: () =>
      collapseExceptionsByTask([
        {
          taskId: 'stuck',
          kind: 'escalation',
          summary: 'attempt 1',
          workerHandle: 'w1',
          attempts: 1,
          at: '2026-08-07T10:00:00Z'
        },
        {
          taskId: 'stuck',
          kind: 'circuit-broken',
          summary: 'breaker open',
          workerHandle: 'w1',
          attempts: 1,
          at: '2026-08-07T10:00:09Z'
        },
        {
          taskId: 'asked',
          kind: 'gate',
          summary: 'Deploy to prod?',
          workerHandle: null,
          attempts: 1,
          at: '2026-08-07T09:00:00Z'
        }
      ]),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the twin body over the kept EXCEPTION_SEVERITY table — collapse key, merged attempt count and severity-then-recency order all identical'
    }
  },
  {
    name: 'fleet-exception-queue.collapseExceptionsByTask([])',
    call: () => collapseExceptionsByTask([]),
    contract: {
      kind: 'parity',
      why: 'the empty list is a real answer here, never a signal — which is exactly why it may not double as one'
    }
  },
  {
    // Reads the Rust table when ready and the TS one when not, so this row is
    // also the drift gate between the two copies of EXCEPTION_SOURCE_STATUS.
    name: 'fleet-exception-queue.unwiredExceptionSources()',
    call: () => unwiredExceptionSources(),
    contract: {
      kind: 'parity',
      why: 'a missing source must reappear in the caveat line in both states, or an empty queue reads as full coverage'
    }
  },
  // Upstream reconciliation: parity is forced on both, because each answer picks
  // a DESTRUCTIVE git command (force-with-lease vs pull; an unattended
  // --ff-only) and mobile never binds the seam, so a signal would be its
  // permanent answer rather than a boot-window one.
  {
    name: 'git-upstream-reconciliation.shouldForcePushWithLeaseForUpstream(diverged)',
    call: () =>
      shouldForcePushWithLeaseForUpstream({
        hasUpstream: true,
        ahead: 2,
        behind: 3,
        behindCommitsArePatchEquivalent: true
      }),
    contract: {
      kind: 'parity',
      why: 'editor.ts syncBranch routes on this — false re-merges the stale commits the lease push exists to replace'
    }
  },
  {
    name: 'git-upstream-reconciliation.isBehindOnlyUpstream(behind only)',
    call: () => isBehindOnlyUpstream({ hasUpstream: true, ahead: 0, behind: 3 }),
    contract: {
      kind: 'parity',
      why: 'Create PR fast-forwards on this unattended, so neither boolean is a safe pre-ready direction'
    }
  },
  {
    // The counter guard's own row: the SHIPPED core reads an absent `ahead` as a
    // real zero and answers TRUE where the twin answers false, so this stays
    // parity only while the shim keeps that class off the wire.
    name: 'git-upstream-reconciliation.isBehindOnlyUpstream(absent ahead)',
    call: () => isBehindOnlyUpstream({ hasUpstream: true, behind: 4 } as never),
    contract: {
      kind: 'parity',
      why: 'a counter that is not a safe integer is answered locally, so ready cannot read `undefined === 0` as true'
    }
  }
]

// An `asserts` shim answers by throwing, so shape it into a comparable value.
function pushTargetOutcome(target: unknown): { ok: boolean; error?: string } {
  try {
    assertGitPushTargetShape(target)
    return { ok: true }
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) }
  }
}

runShimPreReadyContractSuite(CASES)
