// The pre-ready contract gate for the git-wasm shims.
//
// The rule (docs/rust-migration/ported-modules.md, "The pre-ready fallback
// contract"): a shim's not-ready value must be what the deleted TypeScript twin
// would have returned FOR THAT INPUT. The Rust core is a parity port of that
// twin, so the twin's answer is observable — it is the READY answer. That makes
// the rule mechanically checkable with no heuristic: call the shim before
// `initGitWasmForTestFromBytes`, call it again after, compare.
//
// Every row is an observed fact, so this gate cannot false-flag. What it does
// NOT prove is that a caller handles a `sentinel`; that stays a review
// obligation, named in `handledBy`. `divergence` rows are the KNOWN violations
// from the 2026-07 audit, pinned here so a fix flips a test red and gets
// re-declared as `parity` instead of drifting back.
import { readFileSync } from 'node:fs'
import { beforeAll, describe, expect, it } from 'vitest'
import { initGitWasmForTestFromBytes } from './git-line-stats'
import { deriveGeneratedTabTitle } from './agent-tab-title'
import { tuiAgentToAgentKind } from './agent-kind'
import { buildAgentNotificationId } from './agent-notification-id'
import { legacyBaseRefSearchResults } from './base-ref-search-result'
import {
  buildBranchNamePrompt,
  humanizeBranchSlug,
  isAutoGeneratedCreatureBranchName,
  sanitizeBranchSlug,
  stripConfiguredBranchPrefix
} from '../../../../shared/branch-leaf-naming'
import {
  browserViewportPresetToOverride,
  getBrowserViewportPreset
} from './browser-viewport-presets'
import { getCommitMessageModelDiscoveryHostKeyForScope } from './commit-message-host-key'
import {
  isContextualTourId,
  normalizeContextualTourIds
} from '../../../../shared/contextual-tour-id-normalization'
import {
  isPathInsideOrEqual,
  normalizeRuntimePathForComparison,
  relativePathInsideRoot,
  resolveRuntimePath
} from '../../../../shared/cross-platform-path-resolution'
import { normalizeFeatureEducationSource } from './feature-education-telemetry'
import { collapseExceptionsByTask, unwiredExceptionSources } from './fleet-exception-queue'
import {
  hasFeatureInteraction,
  isFeatureInteractionId,
  normalizeFeatureInteractions,
  normalizeFeatureInteractionTelemetryBuckets
} from '../../../../shared/feature-interaction-state'
import {
  getCompletedFeatureTipIds,
  getOrderedUnseenFeatureTips,
  isFeatureTipId,
  normalizeFeatureTipIds
} from '../../../../shared/feature-tip-selection'
import { buildFeatureWallTourDepthSummary } from './feature-wall-tour-depth'
import { getPublishTargetDisplayName } from './git-publish-target-status'
import { assertGitPushTargetShape } from '../../../../shared/git-push-target-shape'
import {
  isBehindOnlyUpstream,
  shouldForcePushWithLeaseForUpstream
} from '../../../../shared/git-upstream-reconciliation'
import { setOrcaDispatchBinding } from '../../../../shared/orca-dispatch-seam'
import { resolveGitHubPRMergeMethods } from './github-pr-merge-methods'
import { gitLabPipelineJobsToPRChecks } from './gitlab-pipeline-checks'
import { resolveHookCommandSourcePolicy } from './hook-command-source-policy'
import { normalizeHostedReviewBaseRef } from './hosted-review-refs'
import {
  buildLinearPersonalApiKeySettingsUrl,
  buildLinearTeamUrl,
  buildLinearWorkspaceApiSettingsUrl
} from '../../../../shared/linear-app-urls'
import {
  hasNativeFileDragTypes,
  resolveNativeFileDropPath
} from '../../../../shared/native-file-drop-routing'
import {
  bucketNestedRepoTelemetryCount,
  buildNestedRepoImportActionTelemetry,
  buildNestedRepoImportResultTelemetry,
  buildNestedRepoScanTelemetry,
  capNestedRepoTelemetryCount,
  shouldEmitNestedRepoImportSubmitTelemetry
} from '../../../../shared/nested-repo-telemetry-payloads'
import { inspectMcpConfigContent } from './mcp-config-content-inspection'
import { MCP_CONFIG_CANDIDATES } from '../../../../shared/mcp-config'
import { normalizeProxyUrl } from './network-proxy'
import {
  encodePairingOffer,
  parsePairingCode,
  type PairingOffer
} from '../../../../shared/pairing-deep-link'
import {
  describeRuntimeCompatBlock,
  evaluateCompat,
  evaluateRuntimeCompat
} from '../../../../shared/protocol-compat-verdict'
import { githubAvatarIcon, sanitizeRepoIcon } from './repo-icon'
import { normalizeRepoBadgeColor, resolveRepoBadgeColor } from './repo-badge-color'
import { getSetupRunnerCommandPlatformForPath } from './setup-runner-command-platform'
import {
  buildSetupRunnerCommand,
  isWslUncPath as isSetupRunnerWslUncPath,
  resolveSetupRunnerCommand
} from '../../../../shared/setup-runner-command-resolution'
import {
  getSyntheticAgentTerminalTitle,
  getSyntheticAgentTitleProfile,
  shouldDriveSyntheticAgentTitleFromHook
} from '../../../../shared/synthetic-agent-title-resolution'
import {
  buildSetupScriptPromptActionTelemetry,
  buildSetupScriptPromptTelemetry
} from './setup-script-telemetry'
import {
  resolveTerminalTabTitle,
  resolveUnifiedTabLabel
} from '../../../../shared/tab-title-ladder'
import { filterAvailableTaskProviders, resolveVisibleTaskProvider } from './task-providers'
import { parseTaskQuery, withQualifier } from './task-query'
import { normalizeTerminalFontWeight, resolveTerminalFontWeights } from './terminal-fonts'
import {
  isWebTerminalSurfaceTabId,
  toHostSessionTabId,
  toWebTerminalSurfaceTabId
} from './terminal-surface-id'
import {
  getTerminalQuickCommandAction,
  normalizeTerminalQuickCommands
} from './terminal-quick-commands'
import { isValidHostTerminalTabId, isValidTerminalTabId } from './terminal-tab-id'
import { slugifyForWorkspaceName } from './workspace-name'
import {
  capTerminalScrollbackSessionBuffer,
  pruneLocalTerminalScrollbackBuffers,
  shouldPreserveTerminalScrollbackBuffers
} from '../../../../shared/workspace-session-terminal-buffer-pruning'
import {
  getRepoIdFromWorktreeId,
  getWorktreePathBasenameFromId,
  splitWorktreeId,
  splitWorktreeIdForFilesystem
} from '../../../../shared/worktree-id-parsing'
import {
  collapseDefaultTuiAgentToBuiltin,
  filterEnabledTuiAgents,
  isTuiAgentEnabled,
  normalizeDisabledTuiAgents,
  pickTuiAgent
} from '../../../../shared/tui-agent-selection-resolution'
import {
  foldWslUncPathCaseInsensitiveParts,
  isWslUncPath,
  mapPosixPathToWslWorktreeUncPath,
  parseWslUncPath,
  toWindowsWslPath
} from '../../../../shared/wsl-unc-paths'
import type { FeatureTipId } from '../../../../shared/feature-tips'
import type { FeatureWallTourDepthInput } from '../../../../shared/feature-wall-tour-depth'
import type {
  TerminalAgentQuickCommand,
  TerminalCommandQuickCommand
} from '../../../../shared/types'

type Contract =
  /** Pre-ready value equals the ready value — the rule, satisfied. */
  | { kind: 'parity'; why: string }
  /** Pre-ready is a declared not-ready SIGNAL the caller branches on. */
  | { kind: 'sentinel'; value: unknown; handledBy: string }
  /** Known violation: pre-ready is a value the caller reads as a real answer. */
  | { kind: 'divergence'; consequence: string }

type PreReadyCase = { name: string; call: () => unknown; contract: Contract }

const TERMINAL_COMMAND: TerminalCommandQuickCommand = {
  id: 'qc-1',
  label: 'Status',
  scope: { type: 'global' },
  action: 'terminal-command',
  command: 'git status',
  appendEnter: true
}

const AGENT_COMMAND: TerminalAgentQuickCommand = {
  id: 'qc-2',
  label: 'Ask',
  scope: { type: 'repo', repoId: 'repo-1' },
  action: 'agent-prompt',
  agent: 'claude',
  prompt: 'review this'
}

// A nested-repo telemetry attempt id: main's schema demands a real UUID.
const NRT_ID = '2fbac1e3-5094-45b4-80a6-90281e6e9e09'

// The done-maps are total Records; "nothing completed yet" is an absent key at
// runtime, so spell it once here rather than enumerating every id.
const NOTHING_DONE = {
  workflowDone: {} as FeatureWallTourDepthInput['workflowDone'],
  stepDone: {} as FeatureWallTourDepthInput['stepDone']
}

const CASES: PreReadyCase[] = [
  {
    name: 'repo-icon.githubAvatarIcon',
    call: () => githubAvatarIcon({ owner: 'octo', repo: 'kit' }),
    contract: {
      kind: 'parity',
      why: 'the fallback rebuilds the same avatar icon inline, so the caller cannot tell'
    }
  },
  {
    name: 'git-publish-target-status.getPublishTargetDisplayName',
    call: () => getPublishTargetDisplayName({ remoteName: 'upstream', branchName: 'feature/foo' }),
    contract: {
      kind: 'parity',
      why: 'the fallback rejoins remote/branch inline — the twin did nothing else, for any input'
    }
  },
  // All four branches of the one exported function, because the fallback
  // reproduces the mapping rather than a constant: a row per branch is what
  // stops it drifting from the core. Parity is mandatory here — the result is a
  // CACHE KEY into persisted settings (discoveredModelsByAgentByHost /
  // selectedModelByAgentByHost), and source-control-ai.ts reads an absent key as
  // LOCAL, so a sentinel would come back as a wrong host key instead of a signal.
  {
    name: 'commit-message-host-key.forScope(undefined)',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope(undefined),
    contract: { kind: 'parity', why: "an undefined scope is 'unknown' in both states" }
  },
  {
    name: 'commit-message-host-key.forScope(null)',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope(null),
    contract: { kind: 'parity', why: "no scope is the 'local' constant the twin returned" }
  },
  {
    name: 'commit-message-host-key.forScope("runtime:env-1")',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope('runtime:env-1'),
    contract: { kind: 'parity', why: 'a runtime scope passes through unchanged in both states' }
  },
  {
    name: 'commit-message-host-key.forScope("conn-1")',
    call: () => getCommitMessageModelDiscoveryHostKeyForScope('conn-1'),
    contract: {
      kind: 'parity',
      why: 'the fallback re-prefixes ssh: inline — the twin did nothing else, for any connection id'
    }
  },
  {
    name: 'github-pr-merge-methods.resolveGitHubPRMergeMethods(null)',
    call: () => resolveGitHubPRMergeMethods(null),
    contract: { kind: 'parity', why: 'no settings is exactly the constant the twin returned' }
  },
  {
    name: 'terminal-fonts.resolveTerminalFontWeights(undefined)',
    call: () => resolveTerminalFontWeights(undefined),
    contract: { kind: 'parity', why: 'unset weight resolves to the same documented default pair' }
  },
  {
    name: 'hook-command-source-policy.resolveHookCommandSourcePolicy(undefined)',
    call: () => resolveHookCommandSourcePolicy(undefined, { hasLocalScript: false }),
    contract: { kind: 'parity', why: 'unconfigured policy is the shared-only constant' }
  },
  {
    name: 'feature-education-telemetry.normalizeFeatureEducationSource(off-table)',
    call: () => normalizeFeatureEducationSource('not-a-source'),
    contract: { kind: 'parity', why: "an off-table source is 'unknown' in both states" }
  },
  // The one shim whose two input classes get different contracts: an absent file
  // is a constant the twin returned unconditionally, real content is a parse plus
  // four DoS bounds computed from the text.
  {
    name: 'mcp-config-content-inspection.inspectMcpConfigContent(candidate, null)',
    call: () => inspectMcpConfigContent(MCP_CONFIG_CANDIDATES[0], null),
    contract: {
      kind: 'parity',
      why: 'the twin returned the missing-file constant for every candidate, reading nothing else'
    }
  },
  {
    name: 'mcp-config-content-inspection.inspectMcpConfigContent(candidate, content)',
    call: () => inspectMcpConfigContent(MCP_CONFIG_CANDIDATES[0], '{"mcpServers":{}}'),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'loadMcpConfigInspections throws McpConfigInspectionUnavailableError instead of inventing a row (a guessed "valid, no servers" would also call a 300 KiB config valid, which is what the size bound refuses); McpConfigSection shows the preparing/unavailable banner and re-runs the load on the availability edge it subscribes to'
    }
  },
  {
    name: 'gitlab-pipeline-checks.gitLabPipelineJobsToPRChecks',
    call: () => gitLabPipelineJobsToPRChecks([]),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'ChecksPanel.fetchGitLabDetails skips the poll update, holds the spinner while pending (the ready edge refetches), and hides ChecksList once availability is terminal — an empty list reads as "No checks configured"'
    }
  },
  {
    name: 'agent-notification-id.buildAgentNotificationId',
    call: () =>
      buildAgentNotificationId({
        worktreeId: 'repo::/userhome/me/orca/workspaces/feature',
        paneKey: 'tab-1:11111111-1111-4111-8111-111111111111',
        stateStartedAt: 1780000000123
      }),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        "use-notification-dispatch omits notificationId from the dispatch payload (main shows the notification, unregistered for dismiss) and ui.ts acknowledgeAgents' `if (id)` adds nothing to the dismiss set"
    }
  },
  {
    name: 'agent-tab-title.deriveGeneratedTabTitle',
    call: () => deriveGeneratedTabTitle('add a login page to the settings screen'),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy: 'the tab keeps its default title; the next store update applies the real one'
    }
  },
  // All three branches of the resolver, because the fallback reproduces the
  // twin's body rather than a constant. Parity is mandatory and a sentinel is
  // impossible: the two-member union has no spare state, and the answer picks the
  // SHELL that executes the setup runner — a wrong 'windows' types
  // `cmd.exe /c "/home/…/run.sh"` at a bash prompt.
  {
    name: 'setup-runner-command-platform.getSetupRunnerCommandPlatformForPath (windows-absolute)',
    call: () =>
      getSetupRunnerCommandPlatformForPath('C:\\repo\\.git\\orca\\setup-runner.cmd', 'posix'),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs isWindowsAbsolutePathLike inline, exactly as the deleted twin did'
    }
  },
  {
    name: 'setup-runner-command-platform.getSetupRunnerCommandPlatformForPath (posix-absolute)',
    call: () =>
      getSetupRunnerCommandPlatformForPath('/remote/repo/.git/orca/setup-runner.sh', 'windows'),
    contract: {
      kind: 'parity',
      why: "the fallback keeps the twin's leading-slash branch, which outranks the caller fallback"
    }
  },
  {
    name: 'setup-runner-command-platform.getSetupRunnerCommandPlatformForPath (caller fallback)',
    call: () => getSetupRunnerCommandPlatformForPath('orca/setup-runner.sh', 'windows'),
    contract: {
      kind: 'parity',
      why: 'a relative path returns the caller-supplied platform unchanged, in Rust and in the fallback'
    }
  },
  // The command the platform above only picks the shell FOR. Parity is forced
  // for the same reason and one step harder: this string is typed into a live
  // shell and runs, and `runnerScriptPathForShell` is what setup-agent-sequencing
  // appends `.<nonce>.done` to, so a pre-ready spelling the shell disagrees with
  // makes the startup gate wait out its two-hour timeout.
  {
    name: 'setup-runner-command-resolution.buildSetupRunnerCommand (git-bash delivery)',
    call: () =>
      buildSetupRunnerCommand('C:\\repo\\.git\\orca\\setup-runner.cmd', 'windows', 'posix'),
    contract: {
      kind: 'parity',
      why: 'the fallback is the deleted twin verbatim — measured equal to the core over 1,853,544 inputs'
    }
  },
  {
    name: 'setup-runner-command-resolution.resolveSetupRunnerCommand (wsl unc rewrite)',
    call: () =>
      resolveSetupRunnerCommand(
        '\\\\wsl.localhost\\Ubuntu\\home\\jin\\run.sh',
        'windows',
        'nushell'
      ),
    contract: {
      kind: 'parity',
      why: 'the UNC branch outranks the shell family in both states, so the marker path stays the Linux one'
    }
  },
  {
    name: 'setup-runner-command-resolution.isWslUncPath (no distro segment)',
    call: () => isSetupRunnerWslUncPath('//wsl.localhost/'),
    contract: {
      kind: 'parity',
      why: "this module's predicate accepts an empty distro where wsl-paths' rejects it — the fallback keeps that difference"
    }
  },
  {
    // Case 3: mode/provider/buckets are all derived from the candidate, so no
    // constant is honest. A schema-VALID guess is the hazard here — the main
    // validator would accept `{mode:'configure_needed',…}` and record it as a
    // real exposure forever, so the only safe pre-ready value is "no event".
    name: 'setup-script-telemetry.buildSetupScriptPromptTelemetry',
    call: () => buildSetupScriptPromptTelemetry({ candidate: null, hasSharedHooks: true }),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'trackSetupScriptPromptExposure returns before adding the prompt key, so the exposure re-fires on a later render instead of being counted wrong'
    }
  },
  {
    name: 'setup-script-telemetry.buildSetupScriptPromptActionTelemetry',
    call: () =>
      buildSetupScriptPromptActionTelemetry({
        action: 'configure_clicked',
        candidate: null,
        hasSharedHooks: false
      }),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'trackSetupScriptPromptAction (SetupScriptPromptCard) skips the track() call; the funnel loses a step rather than gaining a mislabelled one'
    }
  },
  {
    // Case 3: resolve() answers from the input and returns
    // DEFAULT_REPO_BADGE_COLOR only for an INVALID one, so neither the constant
    // (the reverted value) nor null is honest — `undefined` is, because the ready
    // core never returns it.
    name: 'repo-badge-color.resolveRepoBadgeColor("#ff0000")',
    call: () => resolveRepoBadgeColor('#ff0000'),
    contract: {
      kind: 'sentinel',
      value: undefined,
      handledBy:
        'ColorPicker disables its trigger and returns from updateColor/updateDraft/onBlur, so no wheel drag can persist a placeholder; the read-only badge painters fall back to neutral'
    }
  },
  {
    name: 'repo-badge-color.normalizeRepoBadgeColor(invalid)',
    call: () => normalizeRepoBadgeColor('not-a-colour'),
    contract: {
      kind: 'sentinel',
      value: undefined,
      handledBy:
        'ColorPicker gates hasInvalidDraft on the sentinel (no false "Invalid hex color"); store/slices/repos.ts sanitizeRepoUpdate drops badgeColor rather than storing an unvalidated one'
    }
  },
  {
    name: 'terminal-fonts.normalizeTerminalFontWeight(300)',
    call: () => normalizeTerminalFontWeight(300),
    contract: {
      kind: 'divergence',
      consequence:
        'the settings slider commits the normalized value, so any drag persists 500 and discards the user weight'
    }
  },
  {
    name: 'terminal-quick-commands.normalizeTerminalQuickCommands(list)',
    call: () => normalizeTerminalQuickCommands([TERMINAL_COMMAND]),
    contract: {
      kind: 'divergence',
      consequence:
        'the settings slice persists this, so one unrelated settings write empties the saved quick commands'
    }
  },
  {
    name: 'terminal-quick-commands.getTerminalQuickCommandAction(agent)',
    call: () => getTerminalQuickCommandAction(AGENT_COMMAND),
    contract: {
      kind: 'divergence',
      consequence: 'an agent-prompt command is dispatched down the terminal-command branch'
    }
  },
  {
    name: 'hosted-review-refs.normalizeHostedReviewBaseRef("refs/heads/main")',
    call: () => normalizeHostedReviewBaseRef('refs/heads/main'),
    contract: {
      kind: 'divergence',
      consequence: 'the unstripped ref never equals a branch name, so base-ref comparisons miss'
    }
  },
  // Both rows are mandatory parity, not tidy: the resolved string IS the tab's
  // visible identity. TabBar.tsx hands it to resolveCommittedTerminalTitleAgentType,
  // so a wrong answer flips the tab's agent kind, and sync-runtime-graph.ts
  // publishes it to paired mobile clients. The return type is a total string
  // whose `''` already means "nothing usable" — the twin's own default fallback
  // — so no sentinel has anywhere to live. The vault case is spelled out because
  // a port that dropped that one rung is what this row exists to catch.
  {
    name: 'tab-title-ladder.resolveTerminalTabTitle(AI Vault title over a spinner OSC title)',
    call: () =>
      resolveTerminalTabTitle(
        {
          customTitle: null,
          aiVaultTitle: { title: 'Repair provider-native tab titles' },
          generatedTitle: 'Orca generated',
          title: '⠋ albacore'
        },
        true
      ),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the twin ladder inline, vault rung included, over the kept parts types'
    }
  },
  {
    name: 'tab-title-ladder.resolveUnifiedTabLabel(native OpenCode label)',
    call: () =>
      resolveUnifiedTabLabel(
        {
          customLabel: null,
          generatedLabel: 'Fix flaky tests',
          label: 'OC | Native Stable Session'
        },
        true
      ),
    contract: {
      kind: 'parity',
      why: 'same ladder over the label fields, calling the TypeScript isMeaningfulOpenCodeTerminalTitle the twin called'
    }
  },
  {
    name: 'task-query.parseTaskQuery("is:open author:me")',
    call: () => parseTaskQuery('is:open author:me'),
    contract: {
      kind: 'divergence',
      consequence:
        'an empty parse is indistinguishable from a query with no filters — TaskPage shows everything'
    }
  },
  {
    name: 'task-query.withQualifier',
    call: () => withQualifier('', 'state', 'open'),
    contract: {
      kind: 'divergence',
      consequence: 'the filter click silently no-ops (the query is returned unchanged)'
    }
  },
  {
    name: 'network-proxy.normalizeProxyUrl(invalid)',
    call: () => normalizeProxyUrl('not a url'),
    contract: {
      kind: 'divergence',
      consequence: 'ok:true persists an unvalidated proxy URL and hides the validation message'
    }
  },
  {
    name: 'task-providers.filterAvailableTaskProviders',
    call: () =>
      filterAvailableTaskProviders(['github', 'gitlab', 'linear', 'jira'], {
        gitlabInstalled: false,
        linearConnected: false
      }),
    contract: {
      kind: 'divergence',
      consequence: 'unavailable providers stay in the UI — the whole point of the filter'
    }
  },
  {
    name: 'task-providers.resolveVisibleTaskProvider(hidden preference)',
    call: () => resolveVisibleTaskProvider('linear', ['github']),
    contract: { kind: 'divergence', consequence: 'resolves to a provider that is not visible' }
  },
  // Parity is mandatory for both browser-viewport rows: the result is fed
  // straight to window.api.browser.setViewportOverride, so a null pre-ready row
  // would send `override: null` and un-emulate a viewport the menu shows
  // checked — on every dom-ready, for the whole session, if the core failed.
  {
    name: 'browser-viewport-presets.getBrowserViewportPreset("tablet")',
    call: () => getBrowserViewportPreset('tablet'),
    contract: {
      kind: 'parity',
      why: 'the fallback finds the row in the kept BROWSER_VIEWPORT_PRESETS table — the twin did nothing else, for any id'
    }
  },
  {
    name: 'browser-viewport-presets.getBrowserViewportPreset(null)',
    call: () => getBrowserViewportPreset(null),
    contract: {
      kind: 'parity',
      why: 'no preset selected is null in both states, as the twin returned'
    }
  },
  {
    name: 'browser-viewport-presets.browserViewportPresetToOverride(mobile-s)',
    call: () =>
      browserViewportPresetToOverride({
        id: 'mobile-s',
        label: 'Mobile S — 320 × 568',
        width: 320,
        height: 568,
        deviceScaleFactor: 2,
        mobile: true
      }),
    contract: {
      kind: 'parity',
      why: 'the fallback copies the four emulation fields inline — the twin was that projection, for any row'
    }
  },
  // All five are mandatory parity, not tidy: the slug is renamed onto a real
  // branch, the humanized label is persisted as the workspace display name, the
  // prompt is what an agent is spawned on, and `''`/`false` are already each
  // function's real answer, so no sentinel has anywhere to live. The four helper
  // fallbacks proved equal to both shipped cores over 16.1M differential
  // probes — see the shim header.
  {
    name: 'branch-leaf-naming.sanitizeBranchSlug',
    call: () => sanitizeBranchSlug('Fix The Bug!!'),
    contract: { kind: 'parity', why: 'the fallback re-runs the twin kebab-case body inline' }
  },
  {
    name: 'branch-leaf-naming.isAutoGeneratedCreatureBranchName',
    call: () => isAutoGeneratedCreatureBranchName('Nautilus-2'),
    contract: { kind: 'parity', why: 'the fallback looks up the kept MARINE_CREATURES table' }
  },
  {
    name: 'branch-leaf-naming.stripConfiguredBranchPrefix',
    call: () => stripConfiguredBranchPrefix('tmchow-fix-auth', 'Tmchow'),
    contract: { kind: 'parity', why: 'the fallback normalizes and strips the prefix inline' }
  },
  {
    name: 'branch-leaf-naming.humanizeBranchSlug(astral leaf)',
    call: () => humanizeBranchSlug('\u{10428}eseret-branch'),
    contract: {
      kind: 'parity',
      why: 'the fallback uppercases the first code POINT, as the core does — charAt(0) could not'
    }
  },
  {
    name: 'branch-leaf-naming.buildBranchNamePrompt',
    call: () =>
      buildBranchNamePrompt(
        { firstPrompt: '  Add a logout button  ', assistantMessage: '  Wiring it up.  ' },
        '  Prefer product nouns.  '
      ),
    contract: {
      kind: 'parity',
      why: "the fallback joins the twin's sections inline — settings' BUILT_IN_BRANCH_NAME_PROMPT is built at MODULE LOAD, so pre-ready is the only state that popover ever sees"
    }
  },
  {
    // Case 3: the twin strips `origin/`/`upstream/` only when a non-empty
    // remainder follows, so the answer depends on the input and no constant is
    // honest. List-shaped on purpose — a per-row null collapses to `[]`, which
    // the branch picker renders as "No matching branches".
    name: 'base-ref-search-result.legacyBaseRefSearchResults(["origin/main"])',
    call: () => legacyBaseRefSearchResults(['origin/main']),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'searchRuntimeRepoBaseRefDetails and the web preload repos.searchBaseRefDetails throw BaseRefDetailsUnavailableError, so the PR dialog shows "Branch discovery failed." and SmartWorkspaceNameField its branch-search failure line instead of an empty list'
    }
  },
  {
    name: 'agent-kind.tuiAgentToAgentKind("claude")',
    call: () => tuiAgentToAgentKind('claude'),
    contract: { kind: 'divergence', consequence: "telemetry attributes the run to 'other'" }
  },
  {
    name: 'feature-wall-tour-depth.buildFeatureWallTourDepthSummary',
    call: () =>
      buildFeatureWallTourDepthSummary({
        visitedWorkflows: new Set(['start']),
        visitedSteps: new Set(['terminal']),
        workflowDone: NOTHING_DONE.workflowDone,
        stepDone: NOTHING_DONE.stepDone,
        lastGroupId: null
      }),
    contract: {
      kind: 'divergence',
      consequence: 'all-zero counts and a MISSING furthest_step field are emitted as real telemetry'
    }
  },
  {
    name: 'workspace-name.slugifyForWorkspaceName',
    call: () => slugifyForWorkspaceName('My Thing'),
    contract: {
      kind: 'divergence',
      consequence: '\'\' is indistinguishable from "no usable name", so the create form seeds blank'
    }
  },
  {
    name: 'repo-icon.sanitizeRepoIcon(javascript: src)',
    call: () => sanitizeRepoIcon({ type: 'image', src: 'javascript:alert(1)', source: 'custom' }),
    contract: {
      kind: 'divergence',
      consequence: 'the unsafe icon is passed through to the reducer instead of being rejected'
    }
  },
  {
    name: 'terminal-surface-id.toWebTerminalSurfaceTabId',
    call: () => toWebTerminalSurfaceTabId('host-tab-1::leaf-9'),
    contract: {
      kind: 'parity',
      why: 'the fallback re-encodes inline from the kept prefix constant — required, this value keys the tab store and feeds makePaneKey()'
    }
  },
  {
    name: 'terminal-surface-id.toHostSessionTabId(wrapped)',
    call: () => toHostSessionTabId('web-terminal-host-tab-1%3A%3Aleaf-9'),
    contract: {
      kind: 'parity',
      why: 'the fallback is the twin body verbatim — orphan recovery reaps surfaces whose host key does not match, so no sentinel is survivable'
    }
  },
  {
    name: 'terminal-surface-id.toHostSessionTabId(non-prefixed)',
    call: () => toHostSessionTabId('host-tab::leaf'),
    contract: { kind: 'parity', why: 'a non-prefixed id passes through unchanged in both states' }
  },
  {
    name: 'terminal-surface-id.isWebTerminalSurfaceTabId',
    call: () => isWebTerminalSurfaceTabId('web-terminal-abc'),
    contract: {
      kind: 'parity',
      why: 'the fallback is the prefix test itself over the kept constant, so the predicate cannot answer false pre-ready'
    }
  },
  {
    // NOT a pre-ready defect: pre-ready is the twin's answer. This pins the
    // READY side — a port divergence already recorded as `allowDivergence` in
    // tools/parity/vectors/terminal-surface-id.json. On a malformed escape the
    // TS catch returned the WHOLE tabId; orca_core::terminal_surface_id returns
    // the decoded slice. Unreachable for ids minted by
    // toWebTerminalSurfaceTabId (encodeURIComponent output always decodes).
    name: 'terminal-surface-id.toHostSessionTabId("web-terminal-%zz")',
    call: () => toHostSessionTabId('web-terminal-%zz'),
    contract: {
      kind: 'divergence',
      consequence:
        'the Rust core drops the prefix ("%zz") where the twin returned "web-terminal-%zz"; both are non-matching host ids, so a malformed mirrored id is reaped by orphan recovery either way'
    }
  },
  {
    name: 'terminal-tab-id.isValidTerminalTabId("plain-tab")',
    call: () => isValidTerminalTabId('plain-tab'),
    contract: {
      kind: 'parity',
      why: 'the fallback is the twin body over the kept delimiter constant — no sentinel exists for a boolean consumed inside `&&`/`.filter`, and a wrong answer re-keys a live tab'
    }
  },
  {
    name: 'terminal-tab-id.isValidTerminalTabId("host-tab::leaf")',
    call: () => isValidTerminalTabId('host-tab::leaf'),
    contract: {
      kind: 'parity',
      why: 'the rejecting direction too: tabs-hydration must drop a colon-bearing persisted id pre-ready exactly as ready'
    }
  },
  {
    name: 'terminal-tab-id.isValidHostTerminalTabId("web-terminal-abc")',
    call: () => isValidHostTerminalTabId('web-terminal-abc'),
    contract: {
      kind: 'parity',
      why: 'the fallback composes the same prefix test — createTab must not adopt a renderer-local surface id as a host tab hint in either state'
    }
  },
  {
    name: 'terminal-tab-id.isValidHostTerminalTabId("plain-tab")',
    call: () => isValidHostTerminalTabId('plain-tab'),
    contract: {
      kind: 'parity',
      why: 'the accepting direction: a pre-ready false would make createTab mint a fresh UUID and orphan the host PTY binding'
    }
  },
  {
    name: 'git-push-target-shape.assertGitPushTargetShape(valid)',
    call: () => pushTargetOutcome({ remoteName: 'origin', branchName: 'feature/fix' }),
    contract: {
      kind: 'parity',
      why: 'an `asserts` fn has only throw/return, both real answers — the fallback is the twin body over the kept rule constants, so a valid target is never rejected while the seam is unbound'
    }
  },
  {
    name: 'git-push-target-shape.assertGitPushTargetShape(traversal remote)',
    call: () => pushTargetOutcome({ remoteName: 'foo/../bar', branchName: 'feature/fix' }),
    contract: {
      kind: 'parity',
      why: 'the rejecting direction, message included: this is the anti-traversal gate on a value replayed into `git push`, so pre-ready must not fail open'
    }
  },
  {
    name: 'git-push-target-shape.assertGitPushTargetShape(lone surrogate in branch)',
    call: () => pushTargetOutcome({ remoteName: 'origin', branchName: 'feat-\ud800' }),
    contract: {
      kind: 'parity',
      why: 'the codec refuses to encode it in BOTH states, so both take the fallback — the twin accepted it (check-ref-format is the next gate), and the reverted first attempt was exactly this accept turning into a reject naming the wrong field'
    }
  },
  // Parity is mandatory for both, and a sentinel is impossible for either. The
  // real consumer is src/preload/index.ts, which can bind NEITHER binding, so
  // its seam stays unbound for the whole session — the fallback is the behaviour
  // of every OS file drop. hasNativeFileDragTypes is a bare boolean consumed
  // inside `if (!…) return`, and resolveNativeFileDropPath's `null` is a real
  // answer ("no surface claimed it" → an editor drop).
  // Parity is mandatory for all four rows and no sentinel exists: these are the
  // compatibility GATES. A pre-ready "ok" drives every runtime RPC at a server
  // that already said it refuses this client; a pre-ready "blocked" (or a null
  // each caller folds into one) strands every remote host for the session, since
  // an unbound seam after hydration means the wasm FAILED. Both directions of
  // evaluateRuntimeCompat are pinned because the fallback reproduces the twin's
  // body, not a constant.
  {
    name: 'protocol-compat-verdict.evaluateRuntimeCompat(compatible)',
    call: () =>
      evaluateRuntimeCompat({
        clientProtocolVersion: 3,
        minCompatibleServerProtocolVersion: 2,
        serverProtocolVersion: 3,
        serverMinCompatibleClientProtocolVersion: 2
      }),
    contract: {
      kind: 'parity',
      why: "the fallback re-runs the twin's comparisons over the versions the caller passes in — a pre-ready block would disable the host"
    }
  },
  {
    name: 'protocol-compat-verdict.evaluateRuntimeCompat(client-too-old)',
    call: () =>
      evaluateRuntimeCompat({
        clientProtocolVersion: 3,
        minCompatibleServerProtocolVersion: 2,
        serverProtocolVersion: 4,
        serverMinCompatibleClientProtocolVersion: 4
      }),
    contract: {
      kind: 'parity',
      why: 'the blocking direction: the server kill-switch must fire pre-ready exactly as ready, or an incompatible peer is connected'
    }
  },
  {
    name: 'protocol-compat-verdict.describeRuntimeCompatBlock(server-too-old)',
    call: () =>
      describeRuntimeCompatBlock({
        kind: 'blocked',
        reason: 'server-too-old',
        clientProtocolVersion: 3,
        serverProtocolVersion: 1,
        requiredServerProtocolVersion: 2
      }),
    contract: {
      kind: 'parity',
      why: 'the fallback interpolates the same sentence — this string is the whole error the user is shown, and it is thrown as an Error message'
    }
  },
  {
    name: 'protocol-compat-verdict.evaluateCompat(mobile-too-old)',
    call: () =>
      evaluateCompat({
        mobileProtocolVersion: 1,
        minCompatibleDesktopVersion: 0,
        desktopProtocolVersion: 5,
        desktopMinCompatibleMobileVersion: 2
      }),
    contract: {
      kind: 'parity',
      why: 'the desktop-side reference for the mobile protocol: same body, same kill-switch precedence, in both states'
    }
  },
  {
    name: 'native-file-drop-routing.hasNativeFileDragTypes(["Files"])',
    call: () => hasNativeFileDragTypes(['Files']),
    contract: {
      kind: 'parity',
      why: 'the fallback is the twin body over the kept internal-drag-type constant — a pre-ready false would make the preload dragover handler ignore every native drag'
    }
  },
  {
    name: 'native-file-drop-routing.hasNativeFileDragTypes(internal move)',
    call: () => hasNativeFileDragTypes(['Files', 'text/x-orca-file-path']),
    contract: {
      kind: 'parity',
      why: "the rejecting direction: a pre-ready true would hijack Orca's own file-explorer→terminal drags away from their React handlers"
    }
  },
  {
    name: 'native-file-drop-routing.resolveNativeFileDropPath(terminal + leaf)',
    call: () =>
      resolveNativeFileDropPath([
        { terminalPaneLeafId: 'leaf-9' },
        { nativeFileDropTarget: 'terminal', terminalTabId: 'tab-1' }
      ]),
    contract: {
      kind: 'parity',
      why: 'paneLeafId is UNPORTED (orca_core has no such entry field) so the shim composes it on both paths — without it a drop on one split pastes into the active pane instead'
    }
  },
  {
    name: 'native-file-drop-routing.resolveNativeFileDropPath(nearest explorer dir)',
    call: () =>
      resolveNativeFileDropPath([
        { nativeFileDropDir: '/repo/src' },
        { nativeFileDropTarget: 'file-explorer', nativeFileDropDir: '/repo' }
      ]),
    contract: {
      kind: 'parity',
      why: 'the destination dir is the write target for the dropped files, so an innermost-vs-outermost difference would copy them into the wrong folder'
    }
  },
  {
    name: 'native-file-drop-routing.resolveNativeFileDropPath(explorer, no dir)',
    call: () => resolveNativeFileDropPath([{ nativeFileDropTarget: 'file-explorer' }]),
    contract: {
      kind: 'parity',
      why: 'the fail-closed branch: `rejected` drops the gesture, where a pre-ready null would fall through to the editor default and open the files instead'
    }
  },
  {
    name: 'native-file-drop-routing.resolveNativeFileDropPath(unclaimed)',
    call: () => resolveNativeFileDropPath([{ nativeFileDropDir: '/repo' }]),
    contract: {
      kind: 'parity',
      why: "null here is the twin's real answer for this input, not a signal — createNativeFileDropPayload turns it into the editor drop"
    }
  },
  // Synthetic agent titles, a row per exported function. Parity is mandatory and
  // no sentinel exists: main gates driveSyntheticTitleFromHook on the predicate
  // and then writes the profile's labels into the PTY as an OSC 0 sequence, and
  // agent-title-owner rewrites AgentStatusEntry.terminalTitle in mirrored remote
  // entries — a pre-ready answer that is not the ready answer sticks as a wrong
  // (or missing) terminal title for the whole session.
  {
    name: 'synthetic-agent-title-resolution.getSyntheticAgentTitleProfile(codex)',
    call: () => getSyntheticAgentTitleProfile('codex'),
    contract: {
      kind: 'parity',
      why: 'the fallback is an own-key read of the kept profile TABLE, so the labels main writes into the PTY are identical before and after the core lands'
    }
  },
  {
    name: 'synthetic-agent-title-resolution.getSyntheticAgentTitleProfile(unknown agent)',
    call: () => getSyntheticAgentTitleProfile('claude'),
    contract: {
      kind: 'parity',
      why: "null is the twin's real answer for an agent with no profile, not a not-ready signal — main already branches on it and drives no title"
    }
  },
  {
    // Pins the correction, not just the value: `AgentType` is `string & {}`, and
    // the twin's raw `TABLE[agentType]` returned Object.prototype.toString here,
    // which main then wrote into the PTY as `\x1b]0;⠋ undefined\x07`. Both paths
    // answer as orca_core does; a raw index lookup in the fallback turns it red.
    name: 'synthetic-agent-title-resolution.getSyntheticAgentTitleProfile(inherited key)',
    call: () => getSyntheticAgentTitleProfile('toString'),
    contract: {
      kind: 'parity',
      why: 'an inherited Object.prototype member is not a profile on either path'
    }
  },
  {
    name: 'synthetic-agent-title-resolution.getSyntheticAgentTerminalTitle(codex, done)',
    call: () => getSyntheticAgentTerminalTitle('codex', 'done'),
    contract: {
      kind: 'parity',
      why: 'this string IS the OSC 0 title; a pre-ready null would skip the idle frame native OSC already misses'
    }
  },
  {
    name: 'synthetic-agent-title-resolution.getSyntheticAgentTerminalTitle(opencode, waiting)',
    call: () => getSyntheticAgentTerminalTitle('opencode', 'waiting'),
    contract: {
      kind: 'parity',
      why: "null is the twin's real answer — OpenCode owns its semantic session title and a synthesized one would overwrite it"
    }
  },
  {
    name: 'synthetic-agent-title-resolution.shouldDriveSyntheticAgentTitleFromHook(codex, working)',
    call: () => shouldDriveSyntheticAgentTitleFromHook('codex', 'working'),
    contract: {
      kind: 'parity',
      why: "a total predicate with no spare state: false keeps Codex's native spinner, and a pre-ready true would overwrite it on every hook event"
    }
  },
  {
    name: 'synthetic-agent-title-resolution.shouldDriveSyntheticAgentTitleFromHook(devin, done)',
    call: () => shouldDriveSyntheticAgentTitleFromHook('devin', 'done'),
    contract: {
      kind: 'parity',
      why: 'the write-back gate at src/main/index.ts:1436 — a pre-ready false is a session with no synthetic titles at all'
    }
  },
  // The contextual-tour id functions decide `ui.contextualToursSeenIds`, which
  // is PERSISTED: a pre-ready `[]` hydrates an empty seen list and the next
  // updateUI writes it back, replaying every tour the user already dismissed.
  // No sentinel exists — `[]` and `false` are already both functions' real
  // answers — so parity is forced, and the web preload never binds at all.
  {
    name: 'contextual-tour-id-normalization.normalizeContextualTourIds(persisted seen list)',
    call: () =>
      normalizeContextualTourIds(['tasks', 'unknown', 'browser', 'tasks', null, 'automations']),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the twin over the kept CONTEXTUAL_TOUR_IDS table, so the persisted list survives a core that never loads'
    }
  },
  {
    name: 'contextual-tour-id-normalization.isContextualTourId(floating-workspace)',
    call: () => isContextualTourId('floating-workspace'),
    contract: {
      kind: 'parity',
      why: 'the id the core\'s ids const omitted until this cutover — both states must accept every catalog tour, or its "seen" row is dropped on every merge'
    }
  },
  // Path CONTAINMENT decides which worktree owns a file, gates destructive work
  // (ai-vault/session-delete, worktree-removal-safety, relay-watcher-removal-fence)
  // and authorizes filesystem access, so parity is mandatory and a sentinel is
  // impossible: `boolean` and `string | null` (null = "not contained") are total.
  // The mobile client binds no seam at all, so the pre-ready value is the only
  // value it will ever see. One row per shape whose fold is not length-preserving.
  {
    name: 'cross-platform-path-resolution.isPathInsideOrEqual(POSIX sibling prefix)',
    call: () => isPathInsideOrEqual('/repo/app', '/repo/application/src/index.ts'),
    contract: {
      kind: 'parity',
      why: "a boundary-less prefix match would hand another workspace's file to this worktree, and the same predicate authorizes deletes"
    }
  },
  {
    name: 'cross-platform-path-resolution.normalizeRuntimePathForComparison(NFD macOS path)',
    call: () => normalizeRuntimePathForComparison('/userhome/ada/프로젝트'.normalize('NFD')),
    contract: {
      kind: 'parity',
      why: 'the fallback runs the same JS normalize("NFC") the core\'s generated tables were derived from, so a non-ASCII workspace keys its sessions identically in both states'
    }
  },
  {
    name: 'cross-platform-path-resolution.relativePathInsideRoot(WSL UNC alias)',
    call: () =>
      relativePathInsideRoot(
        '\\\\wsl$\\Ubuntu\\home\\Alice\\repo',
        '\\\\wsl.localhost\\ubuntu\\home\\Alice\\repo\\Src'
      ),
    contract: {
      kind: 'parity',
      why: 'callers rejoin this suffix and hit the filesystem with it, and the alias+case fold is not length-preserving — both states must skip whole root SEGMENTS'
    }
  },
  {
    name: 'cross-platform-path-resolution.relativePathInsideRoot(not contained)',
    call: () => relativePathInsideRoot('/repo/app', '/repo/other'),
    contract: {
      kind: 'parity',
      why: 'null is the twin\'s real answer for "outside the root", not a not-ready signal — which is why the shim gates on isOrcaDispatchReady instead of on a null from tryOrcaDispatch'
    }
  },
  {
    name: 'cross-platform-path-resolution.resolveRuntimePath(windows dot segments)',
    call: () => resolveRuntimePath('C:\\Repos\\app\\repo', '..\\worktrees\\feature'),
    contract: {
      kind: 'parity',
      why: 'the result becomes a worktree path on disk, so a pre-ready guess would create or clone into the wrong directory'
    }
  },
  // Terminal-scrollback pruning of PERSISTED session state: parity is mandatory
  // and no sentinel exists. The predicate's two answers are the two halves of
  // the bug (false deletes the only scrollback an SSH pane can cold-restore,
  // true persists megabytes the local daemon already holds), and the prune
  // returns the session itself, so its only spare state would be "never persist
  // this session again". A row per exported function, plus the unhydrated-
  // catalog branch and the multibyte cap that was the last re-port.
  {
    name: 'workspace-session-terminal-buffer-pruning.shouldPreserveTerminalScrollbackBuffers(ssh)',
    call: () =>
      shouldPreserveTerminalScrollbackBuffers('remote-repo::/remote/worktree', [
        { id: 'local-repo', connectionId: null },
        { id: 'remote-repo', connectionId: 'ssh-target-1' }
      ]),
    contract: {
      kind: 'parity',
      why: "TerminalPane's beforeunload capture gate — a pre-ready false drops the SSH pane's buffers on the one write that had them"
    }
  },
  {
    name: 'workspace-session-terminal-buffer-pruning.shouldPreserveTerminalScrollbackBuffers(local host)',
    call: () =>
      shouldPreserveTerminalScrollbackBuffers('host-repo::/worktree', [
        { id: 'host-repo', connectionId: null, executionHostId: 'local' }
      ]),
    contract: {
      kind: 'parity',
      why: "false is the twin's real answer for an explicitly local host, not a not-ready signal"
    }
  },
  {
    name: 'workspace-session-terminal-buffer-pruning.shouldPreserveTerminalScrollbackBuffers(unhydrated catalog)',
    call: () => shouldPreserveTerminalScrollbackBuffers('unknown-repo::/worktree', []),
    contract: {
      kind: 'parity',
      why: 'the fail-safe branch: an unclassifiable worktree keeps its buffers, and a pre-ready false would delete them instead'
    }
  },
  {
    name: 'workspace-session-terminal-buffer-pruning.capTerminalScrollbackSessionBuffer(multibyte over the cap)',
    call: () => capTerminalScrollbackSessionBuffer('é'.repeat(10), 8),
    contract: {
      kind: 'parity',
      why: 'the byte-vs-char cap that was just re-ported: both paths keep 4 accented chars (8 bytes), never 8 chars (16 bytes)'
    }
  },
  {
    name: 'workspace-session-terminal-buffer-pruning.pruneLocalTerminalScrollbackBuffers(mixed local/ssh)',
    call: () =>
      pruneLocalTerminalScrollbackBuffers(
        {
          activeRepoId: 'local-repo',
          activeWorktreeId: null,
          activeTabId: null,
          tabsByWorktree: {
            'local-repo::/local/worktree': [{ id: 'local-tab' }],
            'remote-repo::/remote/worktree': [{ id: 'remote-tab' }]
          },
          terminalLayoutsByTabId: {
            'local-tab': {
              root: null,
              buffersByLeafId: { 'pane:1': 'local-scrollback' },
              scrollbackRefsByLeafId: { 'pane:1': 'v1-local' },
              ptyIdsByLeafId: { 'pane:1': 'local-pty' }
            },
            'remote-tab': {
              root: null,
              buffersByLeafId: { 'pane:1': 'ééééé' },
              ptyIdsByLeafId: { 'pane:1': 'remote-pty' }
            }
          }
          // Cast: the row only needs the two fields the core reads plus one
          // unrelated key, and a whole WorkspaceSessionState would bury them.
        } as unknown as Parameters<typeof pruneLocalTerminalScrollbackBuffers>[0],
        [
          { id: 'local-repo', connectionId: null },
          { id: 'remote-repo', connectionId: 'ssh-target-1' }
        ],
        { bufferByteLimit: 4 }
      ),
    contract: {
      kind: 'parity',
      why: 'this value IS the persisted session: the local tab must lose both buffer maps and the SSH tab must keep a 4-byte tail, identically before and after the core lands'
    }
  },
  // Worktree IDENTITY: parity is mandatory and a sentinel is impossible. Every
  // return type is already total (a string, or `ParsedWorktreeId | null` where
  // null is the twin's real "no `::` here"), the repo id keys reposById /
  // worktreesByRepo, and the parsed path becomes a PTY cwd and a git working
  // directory — both persisted. A row per exported function, plus the branches
  // that carry the folder-workspace suffix.
  {
    name: 'worktree-id-parsing.getRepoIdFromWorktreeId(canonical)',
    call: () => getRepoIdFromWorktreeId('repo-123::/abs/path'),
    contract: {
      kind: 'parity',
      why: 'the fallback is the twin body over the kept separator — a wrong repo id files the worktree under a repo that does not own it'
    }
  },
  {
    name: 'worktree-id-parsing.getRepoIdFromWorktreeId(no separator)',
    call: () => getRepoIdFromWorktreeId('just-a-repo-id'),
    contract: {
      kind: 'parity',
      why: 'a separator-less id IS its own repo id in both states; an empty string here would key the store under ""'
    }
  },
  {
    name: 'worktree-id-parsing.splitWorktreeId(canonical)',
    call: () => splitWorktreeId('repo-123::/abs/path'),
    contract: {
      kind: 'parity',
      why: 'the two slices are rebuilt inline, so the cwd handed to a PTY is identical before and after the wasm lands'
    }
  },
  {
    name: 'worktree-id-parsing.splitWorktreeId(no separator)',
    call: () => splitWorktreeId('just-a-repo-id'),
    contract: {
      kind: 'parity',
      why: 'null is the twin\'s real answer for this input, not a not-ready signal — callers already branch on it as "not a worktree id"'
    }
  },
  {
    name: 'worktree-id-parsing.splitWorktreeIdForFilesystem(folder instance)',
    call: () =>
      splitWorktreeIdForFilesystem('repo::/folder::workspace:123e4567-e89b-12d3-a456-426614174000'),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the kept FOLDER_WORKSPACE_INSTANCE_SUFFIX pattern — leaving the uuid on would hand git and the PTY a directory that does not exist'
    }
  },
  {
    name: 'worktree-id-parsing.getWorktreePathBasenameFromId(posix)',
    call: () => getWorktreePathBasenameFromId('repo-123::/abs/path/nightly-checks'),
    contract: {
      kind: 'parity',
      why: 'composed in the shim over the dispatched split, so both states run the same trim/basename code'
    }
  },
  {
    // Pins the composition decision, not just the value: orca_core trims with
    // Rust's char::is_whitespace and the twin trimmed with JS trim, which differ
    // on U+FEFF (JS only) and U+0085 (Rust only). Wiring this straight to
    // `orca_core::worktree_id::get_worktree_path_basename_from_id` turns the row
    // red instead of quietly rewriting a name persistence.ts flushes into
    // automationRuns[].workspaceDisplayName.
    name: 'worktree-id-parsing.getWorktreePathBasenameFromId(BOM in the leaf name)',
    call: () => getWorktreePathBasenameFromId('repo-123::/abs/path/name\ufeff'),
    contract: {
      kind: 'parity',
      why: "the twin's JS trim stays in TS on BOTH paths because the core does not share it"
    }
  },
  // Nested-repo telemetry, a row per exported function. The three scalar answers
  // MUST be parity: the bucketer is re-derived by main's telemetry superRefine (a
  // signal fails every event's own bucket check) and the submit predicate GATES
  // THE IMPORT, not just the event — both call sites `return` on false. The two
  // builders are sentinels, the setup-script-telemetry shape: a schema-valid guess
  // would be recorded as a real funnel step forever, and nothing retries, so the
  // step is dropped once rather than re-counted when the core lands.
  {
    name: 'nested-repo-telemetry.capNestedRepoTelemetryCount(2.9)',
    call: () => capNestedRepoTelemetryCount(2.9),
    contract: { kind: 'parity', why: 'the twin floor/clamp over the kept count cap' }
  },
  {
    name: 'nested-repo-telemetry.bucketNestedRepoTelemetryCount(7)',
    call: () => bucketNestedRepoTelemetryCount(7),
    contract: {
      kind: 'parity',
      why: 'fed to a VALIDATOR — main drops the event when bucket(count) !== bucket, so only the twin ladder is honest'
    }
  },
  {
    name: 'nested-repo-telemetry.shouldEmitNestedRepoImportSubmitTelemetry(ready)',
    call: () => shouldEmitNestedRepoImportSubmitTelemetry({ attemptId: NRT_ID, selectedCount: 2 }),
    contract: {
      kind: 'parity',
      why: 'a pre-ready false is a dead Import button for the session — both call sites return on it'
    }
  },
  {
    name: 'nested-repo-telemetry.buildNestedRepoScanTelemetry',
    call: () =>
      buildNestedRepoScanTelemetry({
        attemptId: NRT_ID,
        surface: 'sidebar',
        runtimeKind: 'local',
        scan: null
      }),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'the four scan sites (useAddRepoLocalFolderFlow / useAddRepoServerPathFlow / use-add-repo-remote-nested-scan / use-onboarding-flow) skip track("add_repo_nested_scan_result") — one funnel step lost, never a wrong one recorded'
    }
  },
  {
    name: 'nested-repo-telemetry.buildNestedRepoImportActionTelemetry',
    call: () =>
      buildNestedRepoImportActionTelemetry({
        attemptId: NRT_ID,
        surface: 'sidebar',
        runtimeKind: 'local',
        action: 'import_group',
        foundCount: 3,
        selectedCount: 2
      }),
    contract: {
      kind: 'sentinel',
      value: null,
      handledBy:
        'useAddRepoNestedImportFlow / use-onboarding-flow skip track("add_repo_nested_import_action") and CONTINUE the import — the event is optional, the import is not'
    }
  },
  {
    // Unported at the dispatch surface (orca-dispatch has no arm), so it stays
    // TS — but it composes this module's cap/bucket, so the row pins that the one
    // bucket ladder answers identically in both states.
    name: 'nested-repo-telemetry.buildNestedRepoImportResultTelemetry',
    call: () =>
      buildNestedRepoImportResultTelemetry({
        attemptId: NRT_ID,
        surface: 'onboarding',
        runtimeKind: 'runtime',
        mode: 'group',
        foundCount: 4,
        selectedCount: 4,
        result: { importedCount: 2, alreadyKnownCount: 1, failedCount: 1, projects: [] }
      }),
    contract: { kind: 'parity', why: 'both states run one TS body over Rust-backed cap/bucket' }
  },
  // WSL UNC paths: parity is mandatory and no sentinel exists. The distro picks
  // the `wsl -d <distro>` target and the linuxPath becomes a Windows filesystem
  // path, a PTY cwd and a git working directory; both return types are already
  // total (null is the twin's real "not a WSL path", and the predicate is a bare
  // boolean read inside `if`/`&&`), and mobile/preload never bind the seam at
  // all, so a signal would be their permanent answer. A row per exported
  // function, plus both directions of the predicate.
  {
    name: 'wsl-unc-paths.parseWslUncPath(wsl.localhost)',
    call: () => parseWslUncPath('\\\\wsl.localhost\\Ubuntu\\home\\jin\\repo'),
    contract: {
      kind: 'parity',
      why: "the fallback re-runs the twin's kept WSL_UNC_PATH_PATTERN — a wrong distro stats the wrong distro root"
    }
  },
  {
    name: 'wsl-unc-paths.parseWslUncPath(ordinary Windows path)',
    call: () => parseWslUncPath('C:\\Users\\jin'),
    contract: {
      kind: 'parity',
      why: "null is the twin's real answer for a non-WSL path, not a not-ready signal — every caller already branches on it"
    }
  },
  {
    // Pins the correction, not just the value: orca_core splits the tail on '/'
    // where the twin's `.` excluded line terminators, so dispatching this class
    // straight through turns a CR-terminated path the twin refused into a live
    // `wsl -d Ubuntu` target. The shim folds it back to the twin's null.
    name: 'wsl-unc-paths.parseWslUncPath(carriage return in the tail)',
    call: () => parseWslUncPath('//wsl.localhost/Ubuntu/repo\r'),
    contract: {
      kind: 'parity',
      why: 'the twin refused a line-terminator tail and so does the shim, in both states'
    }
  },
  {
    name: 'wsl-unc-paths.isWslUncPath(legacy wsl$)',
    call: () => isWslUncPath('\\\\wsl$\\Ubuntu\\root'),
    contract: {
      kind: 'parity',
      why: 'a pre-ready false would route a WSL worktree down the plain-Windows PTY and path-probe branches'
    }
  },
  {
    name: 'wsl-unc-paths.isWslUncPath(POSIX path)',
    call: () => isWslUncPath('/home/jin/repo'),
    contract: {
      kind: 'parity',
      why: 'the rejecting direction: a pre-ready true would hand a Linux path to the UNC branch'
    }
  },
  {
    // Unported (orca_core has no Linux→Windows counterpart), so it stays TS on
    // both paths; the row pins that it never acquires a not-ready value.
    name: 'wsl-unc-paths.toWindowsWslPath(/mnt drvfs)',
    call: () => toWindowsWslPath('/mnt/c/userhome/jin', 'Ubuntu'),
    contract: { kind: 'parity', why: 'one TS body in both states — nothing crosses the seam' }
  },
  {
    name: 'wsl-unc-paths.mapPosixPathToWslWorktreeUncPath(wsl$ worktree)',
    call: () => mapPosixPathToWslWorktreeUncPath('/etc/hosts', '\\\\wsl$\\Debian\\home\\jin'),
    contract: {
      kind: 'parity',
      why: 'composed over the dispatched parse, so the rebased path a file-open route opens is identical in both states'
    }
  },
  {
    name: 'wsl-unc-paths.foldWslUncPathCaseInsensitiveParts(wsl$ + drvfs tail)',
    call: () => foldWslUncPathCaseInsensitiveParts('\\\\wsl$\\Ubuntu\\mnt\\C\\userhome\\Jin'),
    contract: {
      kind: 'parity',
      why: 'this key is equality-compared against other folded paths, so a pre-ready null would silently miss every match'
    }
  },
  // linear.app URL builders: parity is forced because every answer is handed to
  // window.api.shell.openUrl, and the global `linear.app/settings/…` URL and
  // buildLinearTeamUrl's null are both REAL answers (blank slug / blank key), so
  // neither can double as a signal — a pre-ready one opens the wrong workspace
  // or kills TaskPage's "open team in Linear" action for the session.
  {
    name: 'linear-app-urls.buildLinearTeamUrl(both keys)',
    call: () => buildLinearTeamUrl({ organizationUrlKey: 'acme inc', teamKey: 'A/B' }),
    contract: { kind: 'parity', why: 'the fallback percent-encodes both segments inline' }
  },
  {
    name: 'linear-app-urls.buildLinearTeamUrl(blank team key)',
    call: () => buildLinearTeamUrl({ organizationUrlKey: 'acme', teamKey: '  ' }),
    contract: {
      kind: 'parity',
      why: "null is the twin's real no-key answer, which TaskPage reads as 'this team has no link'"
    }
  },
  {
    name: 'linear-app-urls.buildLinearPersonalApiKeySettingsUrl(slug)',
    call: () => buildLinearPersonalApiKeySettingsUrl('acme inc'),
    contract: { kind: 'parity', why: 'the org-scoped page, not the global one, in both states' }
  },
  {
    name: 'linear-app-urls.buildLinearWorkspaceApiSettingsUrl(no slug)',
    call: () => buildLinearWorkspaceApiSettingsUrl('   '),
    contract: {
      kind: 'parity',
      why: 'the global URL is the answer for a blank slug — and only for a blank slug'
    }
  },
  {
    // Pins the trim SET: JS strips U+FEFF and keeps U+0085, Rust's
    // char::is_whitespace does the opposite, so a slug carrying either must
    // resolve identically on both paths.
    name: 'linear-app-urls.buildLinearWorkspaceApiSettingsUrl(BOM-wrapped slug)',
    call: () => buildLinearWorkspaceApiSettingsUrl('\u{FEFF}acme\u{FEFF}'),
    contract: {
      kind: 'parity',
      why: 'the ECMAScript trim set on both paths, not Unicode White_Space'
    }
  },
  // Feature-interaction state: parity is forced, because the answer is PERSISTED
  // as the interaction state itself — both mergeFeatureInteractionState sites
  // (store/slices/ui.ts, web/web-preload-api.ts) normalize each side and write
  // the merged map back, so a pre-ready `{}` erases the user's recorded history,
  // replays every contextual tour and re-emits every usage bucket. A row per
  // exported function, plus the empty map that must be a real answer and not a
  // signal.
  {
    name: 'feature-interaction-state.normalizeFeatureInteractions(records)',
    call: () =>
      normalizeFeatureInteractions({
        tasks: { firstInteractedAt: 100 },
        browser: { firstInteractedAt: Number.NaN },
        unknown: { firstInteractedAt: 1 }
      }),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the twin loop over the kept catalog — the result is written straight back to the persisted record'
    }
  },
  {
    name: 'feature-interaction-state.normalizeFeatureInteractions(non-object blob)',
    call: () => normalizeFeatureInteractions('nope'),
    contract: {
      kind: 'parity',
      why: "an empty map is the twin's real answer for a fresh/corrupt profile, not a not-ready signal"
    }
  },
  {
    name: 'feature-interaction-state.normalizeFeatureInteractionTelemetryBuckets',
    call: () =>
      normalizeFeatureInteractionTelemetryBuckets({ tasks: 'count_1', browser: 'count_4' }),
    contract: {
      kind: 'parity',
      why: 'this map is the once-only marker gating feature_interaction_usage_bucket_reached — a wrong {} re-counts the fleet'
    }
  },
  {
    name: 'feature-interaction-state.hasFeatureInteraction(recorded)',
    call: () =>
      hasFeatureInteraction({ tasks: { firstInteractedAt: 100, interactionCount: 1 } }, 'tasks'),
    contract: {
      kind: 'parity',
      why: 'a total predicate stored into activeContextualTourWasFeaturePreviouslyInteracted — false replays a tour the user finished'
    }
  },
  {
    name: 'feature-interaction-state.hasFeatureInteraction(not recorded)',
    call: () => hasFeatureInteraction({}, 'browser'),
    contract: {
      kind: 'parity',
      why: 'the rejecting direction: a pre-ready true hides the tour from a user who never used the feature'
    }
  },
  {
    name: 'feature-interaction-state.isFeatureInteractionId(catalog id)',
    call: () => isFeatureInteractionId('tasks'),
    contract: {
      kind: 'parity',
      why: "a zod z.custom refinement and main's IPC gate — a non-boolean reads truthy and admits an arbitrary id"
    }
  },
  {
    name: 'feature-interaction-state.isFeatureInteractionId(off-catalog)',
    call: () => isFeatureInteractionId('nope'),
    contract: {
      kind: 'parity',
      why: 'the rejecting direction: a pre-ready true lets an unknown id into the persisted record'
    }
  },
  // Feature tips: parity ×4, forced. Every answer is total (a boolean, and
  // three lists whose EMPTY value is the twin's real "not an array" / "nothing
  // completed" / "nothing left to show"), and all of them are PERSISTED and
  // never re-derived — the seen list is written back through window.api.ui.set,
  // and use-onboarding-and-feature-tips.ts marks the FIRST ordered tip seen the
  // moment it is shown, so a pre-ready list that is empty, over-long or merely
  // misordered suppresses the wrong tip for good.
  {
    name: 'feature-tip-selection.getOrderedUnseenFeatureTips(nothing seen)',
    call: () => getOrderedUnseenFeatureTips({ seenTipIds: new Set() }),
    contract: {
      kind: 'parity',
      why: 'element 0 is marked seen on show and never un-marked, so a misordered pre-ready list burns the wrong tip forever'
    }
  },
  {
    name: 'feature-tip-selection.getOrderedUnseenFeatureTips(cli installed, cmd-j seen)',
    call: () =>
      getOrderedUnseenFeatureTips({
        seenTipIds: new Set<FeatureTipId>(['cmd-j-palette']),
        completedTipIds: getCompletedFeatureTipIds({
          cliInstalled: true,
          voiceDictationEnabled: false,
          featureInteractions: { 'voice-dictation': { firstInteractedAt: 1, interactionCount: 1 } }
        })
      }),
    contract: {
      kind: 'parity',
      why: "[] is the twin's real 'nothing left to show', so a pre-ready one would open a tip for a feature the user already set up"
    }
  },
  {
    name: 'feature-tip-selection.getCompletedFeatureTipIds(interaction-completed)',
    call: () =>
      getCompletedFeatureTipIds({
        cliInstalled: false,
        voiceDictationEnabled: false,
        featureInteractions: { 'voice-dictation': { firstInteractedAt: 1, interactionCount: 1 } }
      }),
    contract: {
      kind: 'parity',
      why: 'the completion filter feeding the ordered list; only the completing interaction ids cross, so an unread persisted key cannot flip it'
    }
  },
  {
    name: 'feature-tip-selection.normalizeFeatureTipIds(persisted seen list)',
    call: () => normalizeFeatureTipIds(['orca-cli', 'gone', 'orca-cli', 'voice-dictation']),
    contract: {
      kind: 'parity',
      why: 'store hydration and main persistence both run this; a pre-ready [] hydrates an empty seen list that the next markFeatureTipsSeen persists over the real one'
    }
  },
  {
    name: 'feature-tip-selection.isFeatureTipId(catalog id)',
    call: () => isFeatureTipId('cmd-j-palette'),
    contract: {
      kind: 'parity',
      why: "a zod z.custom predicate in main's fail-closed client-UI validator — a pre-ready false rejects a legitimate ui.set write"
    }
  },
  // The ALab exceptions queue: parity, because the empty list a sentinel would
  // collapse to is the SILENT-FAILURE value here. ExceptionsQueue prints
  // "Nothing is waiting on you." for an empty list on a successful poll, so a
  // pre-ready [] tells a supervisor the fleet is clear while a gate is open.
  {
    name: 'fleet-exception-queue.collapseExceptionsByTask(retry storm + gate)',
    call: () =>
      collapseExceptionsByTask([
        {
          taskId: 'stuck',
          kind: 'escalation',
          summary: 'attempt 1',
          workerHandle: 'w1',
          attempts: 1,
          at: '2026-08-07T10:00:00Z'
        },
        {
          taskId: 'stuck',
          kind: 'circuit-broken',
          summary: 'breaker open',
          workerHandle: 'w1',
          attempts: 1,
          at: '2026-08-07T10:00:09Z'
        },
        {
          taskId: 'asked',
          kind: 'gate',
          summary: 'Deploy to prod?',
          workerHandle: null,
          attempts: 1,
          at: '2026-08-07T09:00:00Z'
        }
      ]),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the twin body over the kept EXCEPTION_SEVERITY table — collapse key, merged attempt count and severity-then-recency order all identical'
    }
  },
  {
    name: 'fleet-exception-queue.collapseExceptionsByTask([])',
    call: () => collapseExceptionsByTask([]),
    contract: {
      kind: 'parity',
      why: 'the empty list is a real answer here, never a signal — which is exactly why it may not double as one'
    }
  },
  {
    // Reads the Rust table when ready and the TS one when not, so this row is
    // also the drift gate between the two copies of EXCEPTION_SOURCE_STATUS.
    name: 'fleet-exception-queue.unwiredExceptionSources()',
    call: () => unwiredExceptionSources(),
    contract: {
      kind: 'parity',
      why: 'a missing source must reappear in the caveat line in both states, or an empty queue reads as full coverage'
    }
  },
  // TUI-agent selection: parity is forced on all five, because the answers pick
  // the launch command AND get written back — use-onboarding-flow.ts:197 saves
  // the collapsed default as `defaultTuiAgent`, and normalizeDisabledTuiAgents
  // IS the settings sanitizer at persistence.ts:5893 / slices/settings.ts:90.
  {
    name: 'tui-agent-selection.collapseDefaultTuiAgentToBuiltin(custom profile)',
    call: () =>
      collapseDefaultTuiAgentToBuiltin({ kind: 'custom', id: 'p1' }, [
        { id: 'p1', label: 'Claude (zai)', baseAgent: 'claude', command: 'claude' }
      ]),
    contract: {
      kind: 'parity',
      why: 'the onboarding hydration persists this as the user default agent, so any other pre-ready value is saved over their choice'
    }
  },
  {
    name: 'tui-agent-selection.collapseDefaultTuiAgentToBuiltin(never set)',
    call: () => collapseDefaultTuiAgentToBuiltin(undefined, []),
    contract: {
      kind: 'parity',
      why: 'undefined (never written) must stay distinct from null (explicit auto) in both states — callers spread the answer into props and IPC payloads'
    }
  },
  {
    name: 'tui-agent-selection.pickTuiAgent(stale preference)',
    call: () => pickTuiAgent('gemini', ['cursor', 'codex'], ['claude']),
    contract: {
      kind: 'parity',
      why: 'this is the agent that launches; null already means "nothing qualifies", so it cannot double as a not-ready signal'
    }
  },
  {
    name: 'tui-agent-selection.normalizeDisabledTuiAgents(mixed list)',
    call: () => normalizeDisabledTuiAgents(['codex', 'unknown', 'codex', null, 'claude']),
    contract: {
      kind: 'parity',
      why: 'the sanitizer output is what lands in the settings file, so a pre-ready [] re-enables every agent the user turned off'
    }
  },
  {
    name: 'tui-agent-selection.isTuiAgentEnabled(disabled agent)',
    call: () => isTuiAgentEnabled('codex', ['codex']),
    contract: {
      kind: 'parity',
      why: 'a total predicate consumed inside if/&&, so a pre-ready true offers a disabled agent as a launch target'
    }
  },
  {
    name: 'tui-agent-selection.filterEnabledTuiAgents(one disabled)',
    call: () => filterEnabledTuiAgents(['claude', 'codex', 'grok'], ['codex']),
    contract: {
      kind: 'parity',
      why: 'the picker list itself — [] already means "all disabled", so it cannot double as a signal'
    }
  },
  // Upstream reconciliation: parity is forced on both, because each answer picks
  // a DESTRUCTIVE git command (force-with-lease vs pull; an unattended
  // --ff-only) and mobile never binds the seam, so a signal would be its
  // permanent answer rather than a boot-window one.
  {
    name: 'git-upstream-reconciliation.shouldForcePushWithLeaseForUpstream(diverged)',
    call: () =>
      shouldForcePushWithLeaseForUpstream({
        hasUpstream: true,
        ahead: 2,
        behind: 3,
        behindCommitsArePatchEquivalent: true
      }),
    contract: {
      kind: 'parity',
      why: 'editor.ts syncBranch routes on this — false re-merges the stale commits the lease push exists to replace'
    }
  },
  {
    name: 'git-upstream-reconciliation.isBehindOnlyUpstream(behind only)',
    call: () => isBehindOnlyUpstream({ hasUpstream: true, ahead: 0, behind: 3 }),
    contract: {
      kind: 'parity',
      why: 'Create PR fast-forwards on this unattended, so neither boolean is a safe pre-ready direction'
    }
  },
  {
    // The counter guard's own row: the SHIPPED core reads an absent `ahead` as a
    // real zero and answers TRUE where the twin answers false, so this stays
    // parity only while the shim keeps that class off the wire.
    name: 'git-upstream-reconciliation.isBehindOnlyUpstream(absent ahead)',
    call: () => isBehindOnlyUpstream({ hasUpstream: true, behind: 4 } as never),
    contract: {
      kind: 'parity',
      why: 'a counter that is not a safe integer is answered locally, so ready cannot read `undefined === 0` as true'
    }
  },
  // Pairing deep links: parity ×3, forced, and every row passes an EXPLICIT
  // `nowMs`. The offer's invite window is wall-clock, so a row that let the shim
  // read the clock would compare the pre-ready pass and the ready pass at two
  // different instants and pass or fail on how long this file took to load. A
  // pairing offer names the relay a device will trust and is persisted into the
  // runtime-environment record, so no stand-in is admissible; the third row is
  // the declared IDN residual, whose REFUSAL has to be pre-ready too.
  {
    name: 'pairing-deep-link.encodePairingOffer(relay offer)',
    call: () => pairingOutcome(() => encodePairingOffer(PAIRING_RELAY_OFFER, PAIRING_NOW)),
    contract: {
      kind: 'parity',
      why: 'the fallback re-runs the kept schema at the SAME instant, so the minted link is byte-identical'
    }
  },
  {
    name: 'pairing-deep-link.parsePairingCode(relay code)',
    call: () => parsePairingCode(PAIRING_RELAY_CODE, PAIRING_NOW),
    contract: {
      kind: 'parity',
      why: 'the paste-pair entry point; its offer is written to disk, so a pre-ready guess becomes a trusted relay'
    }
  },
  {
    name: 'pairing-deep-link.encodePairingOffer(xn-- relay origin)',
    call: () =>
      pairingOutcome(() =>
        encodePairingOffer(
          {
            ...PAIRING_RELAY_OFFER,
            relay: { ...PAIRING_RELAY, cellUrl: 'https://xn--80ak6aa92e.com' }
          },
          PAIRING_NOW
        )
      ),
    contract: {
      kind: 'parity',
      why: 'the declared IDN residual: the core refuses it, so the fallback must refuse it rather than accept'
    }
  }
]

/** A fixed instant, and a relay offer minted at it. */
const PAIRING_NOW = 1_783_872_000_000
const PAIRING_RELAY: NonNullable<PairingOffer['relay']> = {
  v: 1,
  directorUrl: 'https://relay.onorca.dev',
  cellUrl: 'https://relay-c1.onorca.dev',
  assignmentEpoch: 7,
  relayHostId: 'AbCdEf0123_-xyZ9',
  inviteToken: 'abcdefghijklmnopqrstuvwxyzABCDEFGH012345678',
  inviteExpiresAt: PAIRING_NOW + 5 * 60 * 1000,
  e2eeFraming: 2
}
const PAIRING_RELAY_OFFER: PairingOffer = {
  v: 2,
  endpoint: 'ws://192.168.1.10:6768',
  deviceToken: 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef',
  publicKeyB64: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  relay: PAIRING_RELAY
}
const PAIRING_RELAY_CODE = encodePairingOffer(PAIRING_RELAY_OFFER, PAIRING_NOW)

/** `encodePairingOffer` rejects by throwing; shape it into a comparable value. */
function pairingOutcome(call: () => unknown): { ok?: unknown; threw?: string } {
  try {
    return { ok: call() }
  } catch (error) {
    return { threw: error instanceof Error ? error.message : String(error) }
  }
}

// An `asserts` shim answers by throwing, so shape it into a comparable value.
function pushTargetOutcome(target: unknown): { ok: boolean; error?: string } {
  try {
    assertGitPushTargetShape(target)
    return { ok: true }
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) }
  }
}

// Serialized so a Set/undefined compares stably; the shims are JSON-boundary
// functions, so a JSON view loses nothing they can return.
function snapshot(call: () => unknown): string {
  return (
    JSON.stringify(call(), (_key, value) => (value instanceof Set ? [...value] : value)) ??
    'undefined'
  )
}

// Why: config/vitest-orca-dispatch-seam.ts binds the shared seam for every test
// file at import time, so a shim that reaches Rust through the seam (rather than
// through this directory's isGitWasmReady/dispatchToWasmCore) would be READY
// during the pre-ready pass and its row would pass vacuously. Unbind first;
// beforeAll's initGitWasmForTestFromBytes → markReady rebinds it.
setOrcaDispatchBinding(null)

const PRE_READY = CASES.map((testCase) => snapshot(testCase.call))

beforeAll(() => {
  initGitWasmForTestFromBytes(readFileSync(new URL('./orca_git_wasm_bg.wasm', import.meta.url)))
})

describe('git-wasm shim pre-ready contract', () => {
  CASES.forEach((testCase, index) => {
    const preReady = PRE_READY[index]!
    const { contract } = testCase

    if (contract.kind === 'parity') {
      it(`${testCase.name} — pre-ready matches ready (${contract.why})`, () => {
        expect(preReady).toBe(snapshot(testCase.call))
      })
      return
    }

    if (contract.kind === 'sentinel') {
      it(`${testCase.name} — signals not-ready (${contract.handledBy})`, () => {
        expect(preReady).toBe(JSON.stringify(contract.value) ?? 'undefined')
        expect(preReady).not.toBe(snapshot(testCase.call))
      })
      return
    }

    it(`${testCase.name} — KNOWN VIOLATION: ${contract.consequence}`, () => {
      // Fix it by making the pre-ready value the ready value, or by turning it
      // into a `sentinel` the caller branches on — then re-declare this row.
      expect(preReady).not.toBe(snapshot(testCase.call))
    })
  })
})
